# Week 1.2 - Pressure-Velocity Coupling
## SIMPLE, PISO and PIMPLE in the Re=100 lid-driven cavity

The lesson connects finite-volume conservation equations to SIMPLE, PISO and PIMPLE, with algebraic examples and recorded cavity comparisons.

[Lecture PDF](https://github.com/Ehsan-Roohi/FlowMLLab/blob/main/lectures/week01_2_pressure_velocity.pdf) | [Executed report](https://github.com/Ehsan-Roohi/FlowMLLab/blob/main/results/week01_2_pressure_velocity/README.md) | [Algorithm/source notes](https://github.com/Ehsan-Roohi/FlowMLLab/blob/main/notebooks/week01_2/README.md)

**Learning outcomes:** derive pressure correction, distinguish linear/coupling/time iterations, preserve mass, compare benchmark errors and measured cost.

**Scope:** Re=100 baseline and retained Re=400/1000 experiments; steady velocity comparisons, mesh refinement and within-step coupling. Transient trajectory accuracy requires a separate time-step study.

**How to use this notebook.** Run cells sequentially. The default executes small algebra examples and loads previously executed (retained) CFD results. Set a `RUN_*` switch to `True` only when ready to launch the corresponding new solve. When opening an updated lesson, start with a fresh Colab runtime: setup reuses an existing checkout. Download any outputs you want to keep before ending a temporary runtime.

In [1]:
from pathlib import Path
import os, sys, subprocess
if "google.colab" in sys.modules or os.environ.get("COLAB_RELEASE_TAG"):
    ROOT = Path("/content/FlowMLLab")
    if not (ROOT / ".git").exists():
        subprocess.run(["git", "clone", "--depth", "1", "https://github.com/Ehsan-Roohi/FlowMLLab.git", str(ROOT)], check=True)
    subprocess.run([sys.executable,"-m","pip","install","-q","-e",str(ROOT)],check=True)
else:
    ROOT = next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/"flowmllab/pressure_velocity.py").exists())
sys.path.insert(0,str(ROOT))
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, Image
from flowmllab.pressure_velocity import CavityConfig, run_cavity, pressure_matrix, divergence
from flowmllab.pressure_velocity_lab import load_results, figures, LABELS
RESULTS = ROOT / "results/week01_2_pressure_velocity"
manifest, recorded = load_results(RESULTS)
print("All recorded field hashes verified.")
print("Recorded source SHA-256:", manifest["source_sha256"])

All recorded field hashes verified.
Recorded source SHA-256: d502568afece2262dbb759c1e315e384cf9c88ac46e98992ee7950a77a0aba5d

### Introduction: A moving lid, a circulating fluid and an unknown pressure
Consider a square container filled with a viscous liquid. Its top wall moves
to the right while the other three walls remain stationary. Friction with
the moving wall starts the liquid moving. The walls prevent it from leaving
the container, so the motion turns into a circulation inside the square.
This is the *lid-driven cavity* problem.

To calculate that motion, we need both the fluid velocity and the pressure
throughout the container. Two physical requirements determine them together.

**Mass conservation.** Imagine a small fixed region inside the liquid.
For an incompressible liquid, whose density stays constant, the amount entering that region must equal the
amount leaving it. Otherwise liquid would accumulate or disappear there.
This requirement is called the *continuity equation*.

**Momentum conservation.** The liquid changes its motion because of
forces. Pressure differences push it, and viscosity transfers motion between
neighboring fluid layers. The *momentum equations* relate those effects
to the fluid acceleration.

Neither requirement alone gives a complete solution. A velocity calculated
with an inaccurate pressure can satisfy a momentum calculation while still
giving unequal inflow and outflow in a small region. We therefore need a
procedure that makes velocity and pressure satisfy both requirements.

**The route through the lesson.**


- Write the continuity and momentum equations for this cavity.

- Divide the domain into small cells and explain the finite-volume method:
      each cell must obey its own conservation balance.

- Locate the stored pressure and velocity values and derive the equations
      that connect neighboring cells.

- Explain how an initial pressure estimate is corrected. Then assemble
      these operations into SIMPLE, PISO and PIMPLE.

- Examine calculated cavity fields, accuracy, convergence and measured cost.

The first calculation uses a Reynolds number
of 100; its definition follows with the governing equations.

### 1: Incompressible flow: conservation laws
Horizontal velocity $u_d(x_d,y_d,t_d)$, vertical velocity $v_d(x_d,y_d,t_d)$ and pressure $p_d(x_d,y_d,t_d)$ are the unknown fields. Subscript $d$ denotes dimensional quantities. For a Newtonian fluid with constant density $\rho$ and constant kinematic viscosity $\nu$, with no body force, continuity is

$$
\frac{\partial u_d}{\partial x_d}+\frac{\partial v_d}{\partial y_d}=0.
$$

Conservation of horizontal and vertical momentum gives

$$
\begin{aligned}
\frac{\partial u_d}{\partial t_d}+u_d\frac{\partial u_d}{\partial x_d}+v_d\frac{\partial u_d}{\partial y_d}
&=-\frac{1}{\rho}\frac{\partial p_d}{\partial x_d}+\nu\left(\frac{\partial^2u_d}{\partial x_d^2}+\frac{\partial^2u_d}{\partial y_d^2}\right),\\
\frac{\partial v_d}{\partial t_d}+u_d\frac{\partial v_d}{\partial x_d}+v_d\frac{\partial v_d}{\partial y_d}
&=-\frac{1}{\rho}\frac{\partial p_d}{\partial y_d}+\nu\left(\frac{\partial^2v_d}{\partial x_d^2}+\frac{\partial^2v_d}{\partial y_d^2}\right).
\end{aligned}
$$

The left sides contain local and convective acceleration. Pressure gradients and viscous diffusion provide the right-side accelerations. These two equations and continuity form the incompressible Navier-Stokes system.

**Scales.** Let $L$ be cavity side length and $U$ the lid speed. Define $x=x_d/L$, $y=y_d/L$, $t=t_dU/L$, $u=u_d/U$, $v=v_d/U$, and $p=(p_d-p_{\rm ref})/(\rho U^2)$. Here $p_{\rm ref}$ is a fixed arbitrary reference pressure. Then $Re=UL/\nu$ and

$$
\begin{aligned}
\frac{\partial u}{\partial x}+\frac{\partial v}{\partial y}&=0,\\
\frac{\partial u}{\partial t}+u\frac{\partial u}{\partial x}+v\frac{\partial u}{\partial y}
&=-\frac{\partial p}{\partial x}+\frac{1}{Re}\left(\frac{\partial^2u}{\partial x^2}+\frac{\partial^2u}{\partial y^2}\right),\\
\frac{\partial v}{\partial t}+u\frac{\partial v}{\partial x}+v\frac{\partial v}{\partial y}
&=-\frac{\partial p}{\partial y}+\frac{1}{Re}\left(\frac{\partial^2v}{\partial x^2}+\frac{\partial^2v}{\partial y^2}\right).
\end{aligned}
$$

The following sections use these dimensionless quantities. At steady state the local time derivatives vanish, while convection, pressure and diffusion still balance.

**Cavity conditions.** The unit-square top lid has $u=1,v=0$; three stationary walls have $u=v=0$. Every wall is impermeable. The ideal moving-lid corners contain a velocity discontinuity, so pressure and vorticity extrema there require care. The introductory case is $Re=100$.

### 2: What the finite-volume method conserves
A *mesh* divides the fluid domain into small regions called cells.
A *control volume* is a fixed region over which we impose a conservation
balance. In this two-dimensional lesson it is a cell area with one unit of
depth perpendicular to the page. A *face* is one boundary segment of
that cell. Two neighboring cells have one face in common.

The finite-volume method starts from the conservation law for each control
volume. It accounts for what is stored inside the region, what crosses its
faces, and any source acting inside it. A *flux* is the amount transported
across a surface per unit area and unit time. Multiplying by face area gives
a transport rate. Here a face length times velocity gives volume flow rate
per unit depth.

For the incompressible cavity, the mass inside a fixed cell is constant.
Its continuity balance is therefore

$$
\boxed{\text{total mass flow rate out of a cell}
       -\text{total mass flow rate into it}=0.}
$$

Momentum has a related balance, with acceleration, pressure forces and viscous
transport as well as momentum carried by fluid crossing the faces.

**How the equations become numerical.**
First integrate a conservation equation over the chosen region. Next express
transport and forces through its faces. Finally approximate the required
face values using a finite set of stored values. The resulting equation is
an algebraic relation between neighboring unknowns. This process is called
*discretization*.

**Why sharing a face matters.** Fluid leaving one cell through an internal
face enters the neighboring cell through that same face. Using one numerical
face flow rate in both balances makes these internal contributions cancel
when the balances are added. Each individual cell must still balance;
cancellation in the whole domain alone is insufficient.

### 2 continued: Finite volume and finite differences
The finite-difference approach used in Week 1 begins with a differential
equation evaluated at grid points. It replaces derivatives by combinations
of nearby samples. For a smooth function $f(x)$ sampled at equally spaced
positions $x_i$, define $f_i=f(x_i)$ and $h=x_{i+1}-x_i$. For example,

$$
\left.\frac{\mathrm df}{\mathrm dx}\right|_{x_i}
\simeq\frac{f_{i+1}-f_{i-1}}{2h}.
$$

This is a centered approximation to a derivative *at a point*.

The finite-volume approach begins with a conservation balance *over a
region*. Its approximations concern the values and gradients needed at the
region's faces. Those gradients can also be evaluated with differences.
Using a difference formula inside a finite-volume method does not change
the fact that the starting equation is a cell conservation balance.

| Question | Finite differences | Finite volume |
| --- | --- | --- |
| Starting form | Differential equation at a grid location | Integrated conservation law for a cell |
| Numerical construction | Approximate derivatives from nearby samples | Approximate face transport and cell terms |
| Conservation check | Depends on the chosen discrete construction | Check the balance of every cell using shared face fluxes |
| This course | Week 1 streamfunction-vorticity solver | Week 1.2 pressure-velocity solver |

On a uniform Cartesian mesh, the two approaches can produce identical
algebraic formulas for some terms, such as constant-coefficient diffusion.
Finite-difference schemes can also be constructed in conservative form.
The distinction is the construction of the discrete equations, not a claim
that one approach always conserves and the other never can.

For the cavity, the next pages choose where to store each unknown. Then the
continuity integral is evaluated over one cell and the momentum integral over
a region associated with one velocity unknown. Their locations and boundaries
are specified before performing those integrations.

### 2 continued: Staggered locations and a pressure control volume
The equations in Section 1 are dimensionless. We now integrate them over a
small fixed region of the grid. A *control volume* is a chosen region of the flow domain. In a
two-dimensional calculation it is an area per unit depth in the third direction.
Pressure $p_P$ is stored at pressure-cell center $P$. Horizontal velocity is
stored at vertical faces; vertical velocity is stored at horizontal faces.
For the cell around $P$, use lowercase $e,w,n,s$ for east, west, north and south
faces. Uppercase $E,W,N,S$ denote neighboring *pressure centers*.
Here a pressure center means the cell center at which pressure is stored.
The *shared velocity face* between $P$ and $E$ is their common vertical
boundary; the horizontal velocity stored there is $u_e$. It is one value used
in the continuity balances of both cells. This storage pattern is the MAC (marker-and-cell)
staggered grid: pressure and the two velocity components occupy different locations.

![mac grid](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/mac_grid.png)

**Figure 1.** Staggered (MAC) storage. Open black circles mark cell centers where pressure is stored; blue filled circles mark horizontal velocities and green triangles mark vertical velocities. The shaded square is the pressure control volume around P, of side length h.

### 2 continued: Geometry and outward directions of one cell
First allow a rectangular cell:

$$
V_P=[x_w,x_e]\times[y_s,y_n],\qquad
\Delta x=x_e-x_w,\quad\Delta y=y_n-y_s,\quad |V_P|=\Delta x\Delta y.
$$

Here $|V_P|$ means its area. The boundary is $\partial V_P$. Its outward unit
normal $\boldsymbol n$ points away from $P$ at each face:

| Face | Outward normal | Face length | Outward velocity component |
| --- | --- | --- | --- |
| East | $(1,0)$ | $\Delta y$ | $+u_e$ |
| West | $(-1,0)$ | $\Delta y$ | $-u_w$ |
| North | $(0,1)$ | $\Delta x$ | $+v_n$ |
| South | $(0,-1)$ | $\Delta x$ | $-v_s$ |

All $u$ values are positive rightward and all $v$ values positive upward.
These coordinate conventions do not reverse at the west or south face.
The minus signs arise from the *outward normal*, rather than from a
different definition of velocity.

The uniform square grid used below has $\Delta x=\Delta y=h=1/N$, where $N$
is the number of pressure cells along one side. Its cell area is $h^2$ and
each face length per unit depth is $h$.

### 2 continued: Why pressure and velocity are staggered
In the preceding grid, a cell center is where pressure is stored. The shared
face is the boundary between two adjacent cells, where the horizontal velocity
is stored. Along one horizontal row, let $x_i$ be center $i$'s position and
$p_i$ its pressure sample. The midpoint $x_{i+1/2}=(x_i+x_{i+1})/2$ is the
position of the face between centers $i$ and $i+1$.

![checkerboard pressure](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/checkerboard_pressure.png)

**Figure 2.** A synthetic pressure diagnostic with h=0.25. (a) Pressure samples at equally spaced cell centers alternate between +1 and -1. (b) Blue circles use the two samples on either side of a cell center; red crosses use the two adjacent samples around their midpoint. The blue result is zero while the red results are +8 or -8. The legend identifies these two difference formulas and their evaluation positions; it does not show two flow solutions.

Panel (b) compares *where* a pressure derivative is evaluated and
*which pair* of stored values is used. Blue circles refer to a centered
derivative at a cell center; red crosses refer to a derivative at the
midpoint between adjacent centers. Their definitions are expanded next.

### 2 continued: Read the two pressure-gradient formulas
Consider a synthetic interior grid patch with $p_i=(-1)^i$. The index $i$
counts pressure samples along $x$; the spacing is $h=0.25$. Neighboring
pressures alternate between $+1$ and $-1$.

If velocity and pressure were both stored at the same centers and the pressure
gradient were approximated by a naive central difference there, it would give

$$
\left(\frac{\partial p}{\partial x}\right)_i
\simeq\frac{p_{i+1}-p_{i-1}}{2h}=0,
$$

because $p_{i+1}=p_{i-1}$. This alternating pressure mode is invisible to that
gradient: the resulting momentum equation cannot distinguish it from zero
pressure gradient in the interior.

On the MAC grid, horizontal momentum is evaluated at the shared face between
adjacent pressure centers. Its pressure gradient is

$$
\left(\frac{\partial p}{\partial x}\right)_{i+1/2}
\simeq\frac{p_{i+1}-p_i}{h}=\pm\frac{2}{h}=\pm8.
$$

The face momentum equation responds to the adjacent pressure difference.
This is one reason for staggering the unknowns. In two dimensions an alternating
pattern in both directions is called a pressure checkerboard.

The figure is a discrete diagnostic pattern, not a computed cavity solution.
Properly stabilized collocated methods can also work; they require their own
face-flux interpolation treatment. The present course implementation uses the
staggered arrangement derived here.

In [1]:
import numpy as np
h = 0.25
p_patch = (-1.0)**np.arange(7)
center_gradient = (p_patch[2:]-p_patch[:-2])/(2*h)
face_gradient = (p_patch[1:]-p_patch[:-1])/h
print("Naive pressure-center gradients:", center_gradient)
print("Shared-face gradients:", face_gradient)
assert np.all(center_gradient == 0.0)
assert np.all(np.abs(face_gradient) == 8.0)

Naive pressure-center gradients: [0. 0. 0. 0. 0.]
Shared-face gradients: [-8.  8. -8.  8. -8.  8.]

### 2 continued: Integral and discrete continuity equations
Start with the differential equation

$$
\frac{\partial u}{\partial x}+\frac{\partial v}{\partial y}=0.
$$

Integrate both terms over the same cell, with $\mathrm dV=\mathrm dx\,\mathrm dy$:

$$
\int_{y_s}^{y_n}\int_{x_w}^{x_e}\frac{\partial u}{\partial x}\,\mathrm dx\,\mathrm dy
+\int_{x_w}^{x_e}\int_{y_s}^{y_n}\frac{\partial v}{\partial y}\,\mathrm dy\,\mathrm dx=0.
$$

For the first term integrate in $x$ while holding $y$ fixed. For the second
integrate in $y$ while holding $x$ fixed. The fundamental theorem of calculus gives

$$
\begin{aligned}
\int_{y_s}^{y_n}[u(x_e,y)-u(x_w,y)]\,\mathrm dy
+\int_{x_w}^{x_e}[v(x,y_n)-v(x,y_s)]\,\mathrm dx=0.
\end{aligned}
$$

Thus a derivative inside the cell becomes the difference of values on its two
opposite faces. Write the velocity vector as $\boldsymbol u=(u,v)$ and the
outward normal as $\boldsymbol n=(n_x,n_y)$. Their dot product
$\boldsymbol u\cdot\boldsymbol n=un_x+vn_y$ is the outward normal speed.
The divergence is $\nabla\cdot\boldsymbol u=\partial u/\partial x+\partial v/\partial y$.
With $\mathrm dS$ denoting a boundary-length element, the same identity is the
divergence theorem in two dimensions:

$$
\int_{V_P}\nabla\cdot\boldsymbol u\,\mathrm dV
=\int_{\partial V_P}\boldsymbol u\cdot\boldsymbol n\,\mathrm dS=0.
$$

Define each face-average
velocity by its face integral; for example,

$$
\overline u_e=\frac{1}{\Delta y}\int_{y_s}^{y_n}u(x_e,y)\,\mathrm dy.
$$

Replacing a face average by the stored face-center sample is the midpoint
approximation used on this grid. With those samples the discrete balance is

$$
\underbrace{\Delta y\,u_e}_{\text{east outflow}}
-\underbrace{\Delta y\,u_w}_{\text{west inflow}}
+\underbrace{\Delta x\,v_n}_{\text{north outflow}}
-\underbrace{\Delta x\,v_s}_{\text{south inflow}}=0.
$$

Each term is a signed volume flux per unit depth. Dividing by cell area gives

$$
\frac{u_e-u_w}{\Delta x}+\frac{v_n-v_s}{\Delta y}=0,
\qquad
\boxed{r_{c,P}=\frac{u_e-u_w+v_n-v_s}{h}=0\quad\text{on a square grid}.}
$$

The residual $r_{c,P}$ is net outward volume flux divided by area. It is not a
pressure change. For constant density $\rho$, multiplication of every flux by
$\rho$ gives the corresponding mass balance.

**Numerical check.** With $h=0.25$ and
$(u_e,u_w,v_n,v_s)=(0.30,0.20,0.10,0.05)$, net outward flux is
$0.25(0.30-0.20+0.10-0.05)=0.0375$ and $r_{c,P}=0.0375/0.25^2=0.60$.
This tentative velocity violates local continuity even if a neighboring cell
has an equal and opposite imbalance. Shared internal fluxes cancel in a global
sum; they must still balance in each individual cell.

### 3: Conservative form and integral momentum balance
The horizontal momentum equation from Section 1 is

$$
\frac{\partial u}{\partial t}+u\frac{\partial u}{\partial x}
+v\frac{\partial u}{\partial y}
=-\frac{\partial p}{\partial x}+\frac{1}{Re}\nabla^2u.
$$

To convert convection into face fluxes, apply the product rule:

$$
\begin{aligned}
\frac{\partial(u^2)}{\partial x}+\frac{\partial(uv)}{\partial y}
&=2u\frac{\partial u}{\partial x}+v\frac{\partial u}{\partial y}
+u\frac{\partial v}{\partial y}\\
&=u\frac{\partial u}{\partial x}+v\frac{\partial u}{\partial y}
+u\underbrace{\left(\frac{\partial u}{\partial x}+\frac{\partial v}{\partial y}\right)}_{0\ \text{by continuity}}.
\end{aligned}
$$

The gradient $\nabla u=(\partial u/\partial x,\partial u/\partial y)$ collects
the two spatial derivatives of the horizontal velocity. Its divergence is
$\nabla\cdot(\nabla u)=\partial^2u/\partial x^2+\partial^2u/\partial y^2$,
the Laplacian in the viscous term. Consequently, the incompressible equation is

$$
\frac{\partial u}{\partial t}+\nabla\cdot(u\boldsymbol u)
=-\frac{\partial p}{\partial x}+\frac{1}{Re}\nabla\cdot(\nabla u).
$$

The scalar $u$ in $u\boldsymbol u$ is the horizontal momentum per unit mass
being transported; $\boldsymbol u=(u,v)$ is the transporting velocity.

Integrate over the *horizontal-velocity* control volume $V_e$, centered
on the stored velocity $u_e$. It is a different region from pressure cell $V_P$.
For a fixed control volume, the time derivative can pass outside the integral.
Apply the divergence theorem separately to convection, pressure and diffusion:

$$
\begin{aligned}
\frac{\mathrm d}{\mathrm dt}\int_{V_e}u\,\mathrm dV
+\int_{\partial V_e}u(\boldsymbol u\cdot\boldsymbol n)\,\mathrm dS
&=-\int_{\partial V_e}p\,n_x\,\mathrm dS
+\frac{1}{Re}\int_{\partial V_e}\nabla u\cdot\boldsymbol n\,\mathrm dS.
\end{aligned}
$$

Here $n_x$ is the horizontal component of the outward unit normal.
The pressure identity used above is

$$
\int_{V_e}\frac{\partial p}{\partial x}\,\mathrm dV
=\int_{\partial V_e}p\,n_x\,\mathrm dS.
$$

| Term | Physical meaning in this equation |
| --- | --- |
| Time derivative | Accumulation of horizontal momentum per unit density |
| Convective integral | Horizontal momentum carried through the boundary by flow |
| Pressure integral | Horizontal pressure force per unit density |
| Diffusive integral | Viscous transport of horizontal momentum |

These integral balances follow from the differential equations. Face quadrature
and interpolation convert them into equations for the stored grid values.

### 3 continued: The momentum volume and its four face contributions
The horizontal velocity $u_e$ lies halfway between pressure centers $P$ and $E$.
Its square momentum volume extends from $x_P$ to $x_E$, a distance $h$.
The pressure centers therefore lie at the midpoints of its west and east faces.

![momentum volume](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/momentum_volume.png)

**Figure 3.** Horizontal-momentum control volume $V_e$. The unknown $u_e$ is at its center, while $p_P$ and $p_E$ are at the west and east face midpoints. Arrows show outward unit normals. The two pressure samples are separated by h.

At this volume's boundaries, write $c_{\rm E},c_{\rm W}$ for the horizontal
advecting velocities and $c_{\rm N},c_{\rm S}$ for the vertical advecting velocities.
All are positive in their coordinate directions. Write $\widehat u_{\rm E}$,
$\widehat u_{\rm W}$, $\widehat u_{\rm N}$, $\widehat u_{\rm S}$ for the
horizontal component being *transported* at those boundaries.
The hat values are interpolated from neighboring velocity samples.

**Convection.** Midpoint evaluation of the four integrals gives

$$
h\left(c_{\rm E}\widehat u_{\rm E}-c_{\rm W}\widehat u_{\rm W}
+c_{\rm N}\widehat u_{\rm N}-c_{\rm S}\widehat u_{\rm S}\right).
$$

North/south transport is still transport of *horizontal* momentum: the
fluid crosses those faces with vertical velocity while carrying horizontal $u$.

**Pressure.** Only the east and west faces have $n_x\ne0$.
Approximating their pressure averages by $p_E$ and $p_P$ gives

$$
-\int_{\partial V_e}p n_x\,\mathrm dS
\simeq -h p_E+h p_P=-h(p_E-p_P).
$$

After dividing by area $h^2$, this is $-(p_E-p_P)/h$.
The separation between $P$ and $E$ is $h$, not $2h$.

**Diffusion.** The normal derivative changes sign on west and south:

$$
\frac{h}{Re}\left[
\left(\frac{\partial u}{\partial x}\right)_{\rm E}
-\left(\frac{\partial u}{\partial x}\right)_{\rm W}
+\left(\frac{\partial u}{\partial y}\right)_{\rm N}
-\left(\frac{\partial u}{\partial y}\right)_{\rm S}\right].
$$

**Accumulation.** Approximate the volume integral by $h^2u_e$, so its
derivative is $h^2\,\mathrm du_e/\mathrm dt$. It vanishes for the target steady
problem. Section 9 introduces the discrete time derivative for a transient calculation.

### 3 continued: Locate the velocity before interpolating it

![hat stored locations](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/hat_stored_locations.png)

**Figure 4.** Stored samples around the horizontal-momentum volume (blue square). Blue circles: horizontal velocity; green triangles: vertical velocity; open black squares: pressure. Coordinates are relative to pressure center P and scaled by h.

Use local coordinates with origin at pressure center $P$. The axes are measured in grid spacings $h$. The pressure
centers are $P=(0,0)$ and $E=(h,0)$. The horizontal velocity $u_e$ is stored
at $(h/2,0)$, on their shared pressure-cell face. Its own momentum control
volume is shifted: $0\leq x\leq h$ and $-h/2\leq y\leq h/2$.

The blue circles are stored horizontal components. For example, $u_{\rm N}$ is
a neighboring horizontal component one spacing above $u_e$, not a vertical
velocity. Green triangles mark stored vertical components. Their averages
supply the speeds carrying fluid through the north and south momentum faces.

### 3 continued: Interpolate the transported horizontal component

![hat interpolated locations](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/hat_interpolated_locations.png)

**Figure 5.** Evaluation points for transported horizontal velocity. Blue circles are stored u samples and red crosses are interpolated values on momentum-volume faces. Dashed segments connect each pair used in an average. The west and east crosses coincide geometrically with pressure centers; pressure symbols are omitted here for clarity.

The red crosses are evaluation points at the faces of the horizontal-momentum
volume. In these face-flux formulas, a hat denotes
interpolation to a momentum-volume face. The east and west crosses coincide with pressure
centers; the north and south crosses lie at pressure-cell corners. These
geometrical coincidences do not make pressure and horizontal velocity the
same variable.

Each cross lies halfway between two blue samples. For example,

$$
\widehat u_{\rm N}=\frac{u_e+u_{\rm N}}2,\qquad
\widehat u_{\rm E}=\frac{u_e+u_{\rm E}}2.
$$

For example, the north cross is at $(h/2,h/2)$, halfway between
$u_e$ at $(h/2,0)$ and $u_{\rm N}$ at $(h/2,h)$. The same construction
applies to the east, west and south faces.

**Read each mark in its equation.** In the face-flux formulas a hat indicates interpolation; a star indicates
a provisional momentum solution; a prime indicates a pressure or velocity
correction. None of these marks independently identifies a pressure-cell center.
The later PIMPLE equations use $q_{\rm lag}^{(\ell)}$ and
$p_{\rm lag}^{(\ell)}$ for the latest outer-iteration estimates, keeping the hat
for spatial interpolation.

### 3 continued: Crossing a face while carrying horizontal momentum

![north face transport](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/north_face_transport.png)

**Figure 6.** Horizontal momentum transported through the north face. The normal speed $c_{\rm N}$ carries fluid upward through the red face; the transported component is the horizontal velocity $\widehat u_{\rm N}$, offset above the face for clarity. $Q_{\rm N}$ is outward volume flux per unit depth. $F^u_{\rm N}$ is horizontal-momentum flux per unit density and unit depth. The values are nondimensional; arrow lengths are schematic.

At the north face, $c_{\rm N}$ is vertical: it carries fluid across the face.
The transported quantity $\widehat u_{\rm N}$ is horizontal. Per unit density
and unit depth, their product times the face length is the integrated
horizontal-momentum flux $h c_{\rm N}\widehat u_{\rm N}$.

**Arithmetic example.** Take nondimensional $h=0.25$ and the stored values

$$
(u_e,u_{\rm E},u_{\rm W},u_{\rm N},u_{\rm S})
=(0.04,0.12,0.02,0.08,-0.02).
$$

The four averages are

$$
(\widehat u_{\rm E},\widehat u_{\rm W},\widehat u_{\rm N},\widehat u_{\rm S})
=(0.08,0.03,0.06,0.01).
$$

Let the normal advecting speeds be $(c_{\rm E},c_{\rm W},c_{\rm N},c_{\rm S})
=(0.08,0.03,0.02,0.07)$. The north value averages $v_{n,P}=0.03$ and
$v_{n,E}=0.01$; the south value averages $v_{s,P}=0.05$ and $v_{s,E}=0.09$.
These values also satisfy continuity in the adjacent pressure cells $P$ and $E$.
The momentum volume's outward volume-flux balance is
$h(0.08-0.03+0.02-0.07)=0$. Its horizontal-momentum balance is different:

$$
\begin{aligned}
h(c_{\rm E}\widehat u_{\rm E}-c_{\rm W}\widehat u_{\rm W}
+c_{\rm N}\widehat u_{\rm N}-c_{\rm S}\widehat u_{\rm S})
&=0.001600-0.000225+0.000300-0.000175\\
&=0.001500.
\end{aligned}
$$

Dividing by area $h^2$ gives the convection term $0.024$. The notebook checks
these values. This is a local interpolation example, not a solved cavity field.

In [2]:
import numpy as np
h = 0.25
u_e, u_E, u_W, u_N, u_S = 0.04, 0.12, 0.02, 0.08, -0.02
u_hat = np.array([(u_e+u_E)/2, (u_W+u_e)/2,
                  (u_e+u_N)/2, (u_S+u_e)/2])  # E, W, N, S
v_nP, v_nE, v_sP, v_sE = 0.03, 0.01, 0.05, 0.09
c = np.array([0.08, 0.03, (v_nP+v_nE)/2, (v_sP+v_sE)/2])
outward_sign = np.array([1, -1, 1, -1])
unsigned_flux = h*c*u_hat
print("Order: E, W, N, S")
print("Interpolated horizontal components:", u_hat)
print("Face transport h*c*u_hat:", unsigned_flux)
print("Net outward momentum transport:", outward_sign @ unsigned_flux)
print("Transport divided by volume h^2:", (outward_sign @ unsigned_flux)/h**2)
assert np.allclose(u_hat, [0.08, 0.03, 0.06, 0.01])
assert np.isclose(outward_sign @ c, 0.0)  # momentum-volume mass balance
assert np.isclose((u_e-u_W+v_nP-v_sP)/h, 0.0)  # pressure cell P
assert np.isclose((u_E-u_e+v_nE-v_sE)/h, 0.0)  # pressure cell E
assert np.isclose(outward_sign @ unsigned_flux, 0.0015)

Order: E, W, N, S
Interpolated horizontal components: [0.08 0.03 0.06 0.01]
Face transport h*c*u_hat: [0.0016   0.000225 0.0003   0.000175]
Net outward momentum transport: 0.0015
Transport divided by volume h^2: 0.024

### 3 continued: Central interpolation and face gradients
In one linear momentum solve, advecting speeds $c$ are evaluated from the
known velocity estimate and then held fixed. This is called freezing the
coefficients. The transported horizontal components remain unknowns. At east and west their
averaging formulas have the same geometry, but their roles in the solve differ.

Let $u_{\rm E},u_{\rm W},u_{\rm N},u_{\rm S}$ be neighboring stored
*horizontal* velocities one grid spacing from $u_e$. They are not the
pressure samples $p_E,p_W,p_N,p_S$. For central interpolation,

$$
\begin{aligned}
\widehat u_{\rm E}&=(u_e+u_{\rm E})/2,&
\widehat u_{\rm W}&=(u_{\rm W}+u_e)/2,\\
\widehat u_{\rm N}&=(u_e+u_{\rm N})/2,&
\widehat u_{\rm S}&=(u_{\rm S}+u_e)/2.
\end{aligned}
$$

The advecting velocities are obtained from the staggered grid:

$$
\begin{aligned}
c_{\rm E}&=(u_e+u_{\rm E})/2,&c_{\rm W}&=(u_{\rm W}+u_e)/2,\\
c_{\rm N}&=(v_{n,P}+v_{n,E})/2,&c_{\rm S}&=(v_{s,P}+v_{s,E})/2.
\end{aligned}
$$

For example, $v_{n,P}$ and $v_{n,E}$ are the vertical velocities on the north
faces of pressure cells $P$ and $E$. During a linear momentum solve the $c$
values are held at their current estimates; updating them is a later nonlinear step.

Approximate the gradients at the momentum-volume faces by

$$
\begin{aligned}
u_{x,{\rm E}}&\simeq(u_{\rm E}-u_e)/h,&
u_{x,{\rm W}}&\simeq(u_e-u_{\rm W})/h,\\
u_{y,{\rm N}}&\simeq(u_{\rm N}-u_e)/h,&
u_{y,{\rm S}}&\simeq(u_e-u_{\rm S})/h.
\end{aligned}
$$

Here $u_{x,{\rm E}}$ means $\partial u/\partial x$ evaluated at the east face.
Substitution and division by $h^2$ turn diffusion into

$$
\beta(u_{\rm E}+u_{\rm W}+u_{\rm N}+u_{\rm S}-4u_e),
\qquad \boxed{\beta=\frac{1}{Re\,h^2}.}
$$

For instance, the east and west contributions combine as
$[(u_{\rm E}-u_e)-(u_e-u_{\rm W})]/(Re\,h^2)$.
The two occurrences of $-u_e$ explain the central $-2u_e$ in that direction.

The full volume-normalized equation is therefore

$$
\begin{aligned}
\frac{\mathrm du_e}{\mathrm dt}
&+\frac{c_{\rm E}(u_e+u_{\rm E})-c_{\rm W}(u_{\rm W}+u_e)}{2h}\\
&+\frac{c_{\rm N}(u_e+u_{\rm N})-c_{\rm S}(u_{\rm S}+u_e)}{2h}\\
&=-\frac{p_E-p_P}{h}
+\beta(u_{\rm E}+u_{\rm W}+u_{\rm N}+u_{\rm S}-4u_e).
\end{aligned}
$$

Each term has the form of an acceleration. Dividing face length $h$ by
cell area $h^2$ accounts for the factors of $1/h$ in these terms.

### 3 continued: Momentum coefficients and numerical example
For the steady interior row, move each convective neighbor term to the right
and each central diffusive term to the left. Introduce $a_e$ for the coefficient
of the velocity being solved, $a_{\rm E},a_{\rm W},a_{\rm N},a_{\rm S}$ for
its four neighbor coefficients, and $b_e$ for known terms collected on the
right side, such as a prescribed wall-velocity contribution. The result is

$$
\boxed{a_eu_e=a_{\rm E}u_{\rm E}+a_{\rm W}u_{\rm W}
+a_{\rm N}u_{\rm N}+a_{\rm S}u_{\rm S}+b_e-\frac{p_E-p_P}{h}.}
$$

An interior steady row has no time or wall source, so $b_e=0$ there.
The neighbor coefficients are

$$
\begin{aligned}
a_{\rm E}&=\beta-c_{\rm E}/(2h),&a_{\rm W}&=\beta+c_{\rm W}/(2h),\\
a_{\rm N}&=\beta-c_{\rm N}/(2h),&a_{\rm S}&=\beta+c_{\rm S}/(2h).
\end{aligned}
$$

For example, the east contribution to convection is
$c_{\rm E}u_e/(2h)+c_{\rm E}u_{\rm E}/(2h)$.
The east diffusion term on the right is $\beta u_{\rm E}-\beta u_e$.
Moving terms gives $(\beta-c_{\rm E}/(2h))u_{\rm E}$ on the right and
$(\beta+c_{\rm E}/(2h))u_e$ on the left. Repeating the operation at all faces gives

$$
\begin{aligned}
a_e&=4\beta+\frac{c_{\rm E}-c_{\rm W}+c_{\rm N}-c_{\rm S}}{2h}\\
&=a_{\rm E}+a_{\rm W}+a_{\rm N}+a_{\rm S}
+\frac{c_{\rm E}-c_{\rm W}+c_{\rm N}-c_{\rm S}}{h}.
\end{aligned}
$$

Do not set the last term to zero merely because the target flow is
incompressible: the current advecting estimates can still have a discrete mass
imbalance. Pressure-velocity coupling removes that imbalance iteratively.
Known wall values contribute to the source and can modify the diagonal.
For a transient problem, the time derivative also supplies a center term and
a known old-time source; those are derived in Section 9.

**One frozen-row example.** Set $h=0.25$, $Re=100$,
$c_{\rm E}=c_{\rm W}=0.02$, $c_{\rm N}=c_{\rm S}=0$.
Then $\beta=0.16$ and

$$
(a_{\rm E},a_{\rm W},a_{\rm N},a_{\rm S})=(0.12,0.20,0.16,0.16),
\qquad a_e=0.64.
$$

For given neighbor values $(u_{\rm E},u_{\rm W},u_{\rm N},u_{\rm S})
=(0.04,0.02,0.03,0.01)$, their weighted sum is

$$
0.12(0.04)+0.20(0.02)+0.16(0.03)+0.16(0.01)=0.0152.
$$

With $p_P=0.010$, $p_E=0.008$ and $b_e=0$, the pressure contribution is
$-(0.008-0.010)/0.25=+0.008$. Thus

$$
\boxed{u_e=(0.0152+0.008)/0.64=0.03625.}
$$

The lower east pressure drives a positive horizontal contribution.
This satisfies one frozen momentum row; it does not by itself enforce the
neighboring pressure cells' continuity equations. That is the purpose of SIMPLE.
For vertical momentum, apply the same construction around $v_n$; its pressure
term is $-(p_N-p_P)/h$. The next section assembles these scalar rows into a matrix.

### 4: Read one discrete momentum equation
The previous section produced an equation for the horizontal velocity $u_e$.
It has one unknown at the center of a horizontal-momentum control volume and
four neighboring horizontal velocities. Before shortening that equation,
identify its entries:

| Entry | Meaning in this row |
| --- | --- |
| $u_e$ | Horizontal velocity being calculated. It is stored at face $e$ between pressure cells $P$ and $E$. |
| $u_{\rm E},u_{\rm W},u_{\rm N},u_{\rm S}$ | Horizontal velocities one mesh spacing east, west, north and south of $u_e$. |
| $a_e$ | Center coefficient multiplying $u_e$. It comes from discretized convection and diffusion. |
| $a_{\rm E},a_{\rm W},a_{\rm N},a_{\rm S}$ | Coefficients multiplying the four neighboring velocities. |
| $b_e$ | Known source contribution after prescribed boundary values have been collected on the right side. |
| $p_P,p_E$ | Pressures at adjacent cell centers, separated by $h$. |

The row is

$$
\begin{aligned}
a_eu_e={}&a_{\rm E}u_{\rm E}+a_{\rm W}u_{\rm W}
          +a_{\rm N}u_{\rm N}+a_{\rm S}u_{\rm S}\\
        &+b_e-\frac{p_E-p_P}{h}.
\end{aligned}
$$

The neighbor terms describe interaction with the surrounding flow. The last
term is the horizontal pressure force per unit mass. All rows here have
already been divided by control-volume area; their terms have the
dimensionless form of accelerations.

**Where the source comes from.** At a steady interior location, there is
no prescribed wall value in the row and this cavity has no body-force source:
$b_e=0$. At the moving lid, the stored velocity is a distance $h/2$ below the
prescribed wall velocity $U_{\rm wall}$. Approximate the normal diffusive
gradient using that half-cell distance. The north-face contribution, divided
by the momentum-volume area, is

$$
\frac{1}{Re}\frac{h}{h^2}\frac{U_{\rm wall}-u_e}{h/2}
=2\beta U_{\rm wall}-2\beta u_e,\qquad \beta=\frac{1}{Re\,h^2}.
$$

Move $-2\beta u_e$ to the left: it contributes $+2\beta$ to the diagonal.
The known term $2\beta U_{\rm wall}$ stays on the right and enters $b_e$.
For $Re=100$, $h=0.25$ and $U_{\rm wall}=1$, these wall contributions are
$0.32$ to the diagonal and $0.32$ to the source. The complete wall row also
includes its remaining face contributions. The symbol $b_e$ collects known
terms; it is not another unknown. Time-dependent sources are introduced
with the time discretization in Section 9.

### 4 continued: A source, a neighbor sum and one velocity
The quantity needed from the neighboring velocities is their weighted sum
plus the known source. Call it $H_e$:

$$
H_e=b_e+a_{\rm E}u_{\rm E}+a_{\rm W}u_{\rm W}
        +a_{\rm N}u_{\rm N}+a_{\rm S}u_{\rm S}.
$$

Define $d_e=1/a_e$, the reciprocal of the center coefficient. Dividing the
momentum row by $a_e$ now gives

$$
\boxed{u_e=d_e\left(H_e-\frac{p_E-p_P}{h}\right).}
$$

For fixed coefficients, changing a neighbor velocity changes $H_e$.
Changing the pressure difference changes the pressure contribution. These are
the two pieces used repeatedly in pressure-velocity coupling.

Use the preceding interior example: $a_e=0.64$, $b_e=0$, and
$(a_{\rm E},a_{\rm W},a_{\rm N},a_{\rm S})=(0.12,0.20,0.16,0.16)$.
With neighboring velocities $(0.04,0.02,0.03,0.01)$,

$$
H_e=0+0.12(0.04)+0.20(0.02)+0.16(0.03)+0.16(0.01)=0.0152.
$$

For $p_P=0.010$, $p_E=0.008$ and $h=0.25$,

$$
\begin{aligned}
\frac{p_E-p_P}{h}&=-0.008, & d_e&=1/0.64=1.5625,\\
u_e&=1.5625[0.0152-(-0.008)]=0.03625.
\end{aligned}
$$

This is the same scalar momentum calculation, with its terms grouped under
two names. It does not yet enforce the four-face continuity balance in
each pressure cell.

**Generalizing the location.** Let $f$ label any unknown velocity location
and write its component as $q_f$: either a horizontal $u$ or a vertical $v$.
Let $g$ label a neighboring location contributing to that same component row.
The set of such neighbors is $\mathrm{NB}(f)$, and $a_{fg}$ multiplies $q_g$.
Then

$$
H_f=b_f+\sum_{g\in\mathrm{NB}(f)}a_{fg}q_g,\qquad d_f=1/a_f.
$$

The sum adds the neighbor contributions just evaluated explicitly.
The generic symbol $q_f$ represents a velocity component, not a volume flow rate.

### 4 continued: Collect the scalar rows into a linear system
A *vector* is an ordered column of values. Collect all unknown interior
horizontal and vertical face velocities into the column $q$. Collect the
cell-center pressures into $p$ and the known source entries $b_f$ into $b$.
Use the same ordering every time these columns are assembled.

A *matrix* stores the coefficients multiplying that column of unknowns.
For the momentum matrix $A$, put $a_f$ on row $f$'s diagonal. Move the neighbor
terms to the left, so its neighbor entries are $-a_{fg}$:

$$
(Aq)_f=a_fq_f-\sum_{g\in\mathrm{NB}(f)}a_{fg}q_g.
$$

The notation $(Aq)_f$ means entry $f$ of the product $Aq$. It is precisely
the left side of one rearranged scalar momentum equation.

Define $G$ as the discrete pressure-gradient operation. It maps the stored
pressures to a pressure gradient at each unknown velocity location. For example,

$$
(Gp)_e=\frac{p_E-p_P}{h},\qquad
(Gp)_n=\frac{p_N-p_P}{h}.
$$

The first entry acts in horizontal momentum and the second in vertical
momentum. The complete set of rows is therefore

$$
\boxed{Aq=b-Gp.}
$$

This abbreviates the equations already derived. Once coefficients, boundary
values and a pressure estimate are specified, a linear solver calculates
the velocity column.

For the square mesh with $N$ pressure cells along each side, there are $N^2$
pressures. Unknown interior velocities comprise $N(N-1)$ horizontal and
$N(N-1)$ vertical values. Thus $q$ and $b$ each have $2N(N-1)$ entries,
and $A$ has that many rows and columns. Prescribed wall-normal velocities
are boundary data, rather than entries in $q$.
The Python arrays retain those boundary values as well: pressure has shape
$(N,N)$, horizontal velocity $(N,N+1)$ and vertical velocity $(N+1,N)$.
Array entry $[j,i]$ uses row $j$ for the $y$ direction and column $i$ for $x$.
The column $q$ used in the algebra contains only the interior unknown entries
extracted from those full arrays.

### 4 continued: The operators used by the coupling algorithms
Define the discrete divergence operation $D$ by applying the derived cell
continuity balance to the stored face velocities:

$$
(Dq)_P=\frac{u_e-u_w+v_n-v_s}{h}=r_{c,P}.
$$

Thus $Dq$ is a column of cell imbalances, one entry per pressure cell.
Zero in every entry means discrete continuity. The gradient $G$ maps pressure
values to face gradients; $D$ maps face velocities back to cell balances.

Call the diagonal part of the momentum matrix $M$, the remaining part $R$,
and the inverse of the diagonal $d$:

$$
M=\operatorname{diag}(a_f),\qquad R=A-M,\qquad
d=M^{-1}=\operatorname{diag}(1/a_f).
$$

The notation $\operatorname{diag}(a_f)$ means a matrix containing the center
coefficients on its diagonal and zeros elsewhere. The inverse $d$ simply
divides entry $f$ by $a_f$. The matrix $R$ contains the off-diagonal entries
$-a_{fg}$, so

$$
H(q)=b-Rq,\qquad q=d[H(q)-Gp].
$$

In entry $f$, $-Rq$ restores the positive neighbor sum used in $H_f$.
The notation $H(q)$ emphasizes that these contributions change when the
neighbor velocities change. Coefficients stay fixed during one linear solve;
convection coefficients are rebuilt between nonlinear updates.

| Symbol | Operation and input/output |
| --- | --- |
| $A,b$ | Momentum coefficients and known sources; $Aq=b-Gp$. |
| $G$ | Cell pressures in; pressure gradients at velocity faces out. |
| $D$ | Face velocities in; cell continuity residuals out. |
| $d$ | Scale each velocity-row entry by its reciprocal center coefficient. |
| $R$ | Off-diagonal momentum coefficients, carrying neighbor coupling. |
| $H(q)$ | Known sources plus neighbor-velocity contributions. |

Pressure is solved at cell centers and velocity at faces, so $D$ and $G$
map between different collections of values. Section 6 derives the pressure
matrix from these operations. The small letter $d$ is distinct from the grid
spacing $h$.

### 5: Why a momentum solution needs a pressure correction
Suppose the velocity and pressure estimates have already been updated $k$
times. Superscript $k$ labels that steady coupling iteration. It is not a
physical time level. The current pressure column is $p^k$.

Hold the momentum coefficients fixed and solve

$$
Aq^*=b-Gp^k.
$$

The star labels the *predictor*: the velocity obtained using this pressure
estimate. It is provisional because the momentum solve alone does not impose
continuity in every cell. Compute its cell residuals from $Dq^*$.

For one square pressure cell with $h=0.25$, suppose its predicted velocities are

$$
(u_e^*,u_w^*,v_n^*,v_s^*)=(0.12,0.08,0.01,0.03).
$$

The star on each component has the same predictor meaning. The integrated
outward volume flow rate per unit depth, called $Q_P^*$, is

$$
Q_P^*=h(u_e^*-u_w^*+v_n^*-v_s^*)
=0.25(0.12-0.08+0.01-0.03)=0.005.
$$

Dividing by cell area gives the continuity residual,

$$
r_{c,P}^*=Q_P^*/h^2=0.005/0.0625=0.08.
$$

More fluid leaves than enters. The face velocities must change so that their
combined outward flow changes by $-0.005$. Pressure correction is obtained
from this conservation requirement over all cells, rather than guessed from
this number alone.

Let $p_{\rm corr}$ denote the pressure sought by this correction solve, and
$q_{\rm corr}$ its corrected velocity. Define their increments by

$$
p'=p_{\rm corr}-p^k,\qquad q'=q_{\rm corr}-q^*.
$$

A prime denotes an additive change, not a derivative. Equivalently,

$$
\boxed{\Delta p=p_{\rm corr}-p^k=p'.}
$$

This is a pressure change at a fixed cell between estimates.
The difference $p_E-p_P$ compares pressures at two locations in one estimate.
The residual $r_{c,P}^*$ instead measures a velocity imbalance. These three
quantities have different roles and must not be interchanged.

### 5 continued: Derive the velocity correction from one momentum row
For horizontal face $e$, the predictor equation is

$$
a_eu_e^*=\sum_{g\in\mathrm{NB}(e)}a_{eg}q_g^*
          +b_e-\frac{p_E^k-p_P^k}{h}.
$$

Use the same coefficients for a corrected solution. Substitute
$u_{e,\rm corr}=u_e^*+u'_e$, $q_{g,\rm corr}=q_g^*+q'_g$ and
$p_{P,\rm corr}=p_P^k+p'_P$, with the analogous expression at $E$:

$$
\begin{aligned}
a_e(u_e^*+u'_e)={}&\sum_{g\in\mathrm{NB}(e)}a_{eg}(q_g^*+q'_g)+b_e\\
 &-\frac{(p_E^k+p'_E)-(p_P^k+p'_P)}{h}.
\end{aligned}
$$

Subtract the predictor row. The known source $b_e$, predictor neighbor terms
and old pressure gradient cancel, leaving

$$
a_eu'_e=\sum_{g\in\mathrm{NB}(e)}a_{eg}q'_g-\frac{p'_E-p'_P}{h}.
$$

This exact correction equation couples corrections at neighboring velocity
locations. For all velocity rows it is $Aq'=-Gp'$.

**The SIMPLE approximation.** For the local velocity correction,
neglect the neighbor-correction sum. The center response remains:

$$
a_eu'_e\simeq-\frac{p'_E-p'_P}{h},\qquad
\boxed{u'_e=-d_e\frac{p'_E-p'_P}{h}},\qquad d_e=1/a_e.
$$

This approximates the momentum response to a pressure increment. It does not
remove the requirement to conserve mass. The pressure equation is chosen so
that the resulting face corrections satisfy every cell's continuity balance.

The same construction at the other three faces gives

$$
\begin{aligned}
u'_w&=-d_w\frac{p'_P-p'_W}{h},\\
v'_n&=-d_n\frac{p'_N-p'_P}{h},&
v'_s&=-d_s\frac{p'_P-p'_S}{h}.
\end{aligned}
$$

Each $d$ is the reciprocal diagonal of that face's own momentum row. Corrected
continuity on a square cell requires

$$
0=r_{c,P}^*+\frac{u'_e-u'_w+v'_n-v'_s}{h}.
$$

Section 6 substitutes the four expressions into this balance to obtain
the pressure equation. Repeated coupling iterations also restore consistency
with the full momentum equations, whose neighbor corrections were approximated.

### 5 continued: One shared face, one velocity correction

![shared face correction](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/shared_face_correction.png)

**Figure 7.** A shared-face pressure correction. When $p_E^\prime$ exceeds $p_P^\prime$ by 0.01, the velocity increment is westward: $u_e^\prime=-0.02$. The predictor 0.12 becomes 0.10. The same face velocity enters the two neighboring outward flux balances with opposite signs.

The predictor $u_e^*$ is obtained from momentum with the current pressure
estimate. It generally leaves a cell mass imbalance. A pressure correction
$p^\prime$ produces a velocity increment $u_e^\prime$:

$$
u_e=u_e^*+u_e^\prime,\qquad
u_e^\prime=-d_e\frac{p_E^\prime-p_P^\prime}{h},\qquad d_e=1/a_e>0.
$$

Here $a_e$ is the diagonal of the *volume-normalized* momentum equation.
The prime denotes an increment, not differentiation. If $p_E^\prime>p_P^\prime$,
the correction acts westward, consistent with acceleration down a pressure
gradient.

Cell $P$ and cell $E$ use the same shared face value. In the outward flux
balance it contributes $+h u_e$ for $P$ and $-h u_e$ for $E$. A shared-face
correction therefore preserves pairwise cancellation between neighboring cells.
The pressure equation chooses these corrections to remove each cell's
predictor mass imbalance, subject to the boundary fluxes and pressure reference.

Return to the predictor mass-balance example in Section 5, where $u_e^*=0.12$ and
$r_{c,P}^*=0.08$. For this correction illustration, assume $a_e=2$, so
$d_e=0.5$, and suppose the pressure solve returns
$p_E^\prime-p_P^\prime=0.01$. Then

$$
u_e^\prime=-0.5(0.01)/0.25=-0.02,\qquad u_e=0.12-0.02=0.10.
$$

Holding the other faces fixed, cell $P$ loses $h(0.02)=0.005$ of outward
volume flux: its imbalance becomes zero. The same face change increases
cell $E$'s outward flux by $0.005$. A correction that fixes $P$ alone may
therefore spoil $E$; all pressure cells must be solved together.
The prescribed diagonal $a_e=2$ belongs to this correction illustration,
not to the earlier convection-flux example.

### 6: The cell pressure equation and its boundary data
At each face, the corrected velocity is tentative velocity plus its correction:

$$
\begin{aligned}
u_e&=u_e^*-\frac{d_e}{h}(p'_E-p'_P),&
u_w&=u_w^*-\frac{d_w}{h}(p'_P-p'_W),\\
v_n&=v_n^*-\frac{d_n}{h}(p'_N-p'_P),&
v_s&=v_s^*-\frac{d_s}{h}(p'_P-p'_S).
\end{aligned}
$$

Insert these into $(u_e-u_w+v_n-v_s)/h=0$. The west and south terms change sign because their velocities enter cell outflow with minus signs:

$$
\begin{aligned}
0=r_{c,P}^*&-\frac{d_e}{h^2}(p'_E-p'_P)
+\frac{d_w}{h^2}(p'_P-p'_W)\\
&-\frac{d_n}{h^2}(p'_N-p'_P)
+\frac{d_s}{h^2}(p'_P-p'_S).
\end{aligned}
$$

Collect the coefficients of each pressure correction and move the tentative residual to the right:

$$
\begin{aligned}
&\frac{d_e+d_w+d_n+d_s}{h^2}p'_P\\
&\quad-\frac{d_ep'_E+d_wp'_W+d_np'_N+d_sp'_S}{h^2}
=-r_{c,P}^*.
\end{aligned}
$$

The center coefficient is the sum of four face weights; each neighbor has a negative coefficient. The right side is the negative cell divergence of the tentative velocity. The same face weight must be shared by its two adjacent pressure cells.

**Matrix form.** Name the resulting pressure matrix $L$. It has one row
per pressure cell and multiplies the column of cell pressure corrections.
This operator symbol is distinct from the cavity length used in Section 1's
dimensional scaling. Applying $D$ to $q=q^*-dGp'$ gives

$$
\begin{aligned}
0&=Dq^*-DdGp',\\
L&=-DdG,\\
Lp'&=-Dq^*.
\end{aligned}
$$

The positive-diagonal convention for $L$ explains the minus sign on the right. Once pressure is solved, the face correction $-dGp'$ cancels the computed cell imbalance, up to linear-solve error.

### 6 continued: Boundary cells and pressure reference
**Impermeable walls.** The normal wall velocity is prescribed and is not an unknown interior face velocity. Its normal correction is zero. A prescribed wall-normal face contributes zero correction weight, so that face coefficient is omitted from the boundary-cell pressure row. Pressure assembly therefore has no correction flux across the external wall. For a cell adjacent to a stationary west wall, $u_w^*=u'_w=0$, so its row is

$$
\frac{d_e+d_n+d_s}{h^2}p'_P
-\frac{d_ep'_E+d_np'_N+d_sp'_S}{h^2}=-r_{c,P}^*.
$$

There is no west pressure-neighbor term. At a corner, omit both prescribed wall-normal face weights. Zero normal correction does not mean zero pressure at every wall.

**Pressure reference.** The vector $\boldsymbol 1$ contains one in every pressure entry. Adding a constant to every cell pressure changes no pressure gradient: $G\boldsymbol 1=0$. Consequently $L\boldsymbol 1=0$ and the closed-cavity pressure system has one arbitrary constant. Pinning means temporarily prescribing one pressure unknown, for example $p_{\rm ref\ cell}=0$, to make the linear solve unique. The implementation then removes the arithmetic cell mean:

$$
\overline p=\frac{1}{N^2}\sum_Pp_P,\qquad
\widetilde p_P=p_P-\overline p.
$$

The same constant is subtracted from every cell, so

$$
\widetilde p_E-\widetilde p_P=(p_E-\overline p)-(p_P-\overline p)=p_E-p_P.
$$

The gradient and corrected velocity are unchanged. The reported zero-mean pressure is a gauge choice, not an extra boundary force.

Tangential no-slip is enforced in momentum through wall diffusion. On the staggered grid it is distinct from the zero normal correction used in the cell mass balance.

In [2]:
cfg = CavityConfig(method="simple",cells=32)
n = cfg.cells
print("p shape:",(n,n),"u shape:",(n,n+1),"v shape:",(n+1,n))
L = pressure_matrix(np.ones((n,n-1)),np.ones((n-1,n)),1/n)
print("Constant-pressure nullspace defect:",np.max(np.abs(L @ np.ones(n*n))))
assert np.max(np.abs(L @ np.ones(n*n))) < 1e-10

p shape: (32, 32) u shape: (32, 33) v shape: (33, 32)
Constant-pressure nullspace defect: 0.0

### 7: Two-cell pressure-correction example
Consider two closed square cells with one shared vertical face. This is an algebraic conservation example, not a resolved cavity. The pressure guess is initially zero in both cells. Let $h=0.5$, tentative shared velocity $u^*=0.2$, and inverse momentum diagonal $d_e=0.1$. Positive shared velocity leaves cell 1 and enters cell 2. All external normal velocities are zero.

$$
r_{c,1}^*=\frac{0.2}{0.5}=0.4,\qquad
r_{c,2}^*=\frac{-0.2}{0.5}=-0.4.
$$

For these two cells, $q=u$ has one entry. The divergence and gradient matrices are

$$
D=\begin{bmatrix}1/h\\-1/h\end{bmatrix},\qquad
G=\begin{bmatrix}-1/h&1/h\end{bmatrix}.
$$

The first row of $D$ gives outflow from cell 1; the second gives inflow to cell 2.
The row $G$ gives $(p_2-p_1)/h$ at their shared velocity face. Consequently,

$$
L=-D d_e G=\frac{d_e}{h^2}\begin{bmatrix}1&-1\\-1&1\end{bmatrix},
\qquad d_e/h^2=0.1/0.25=0.4.
$$

Thus $Lp'=-Dq^*$ is

$$
0.4\begin{bmatrix}1&-1\\-1&1\end{bmatrix}
\begin{bmatrix}p'_1\\p'_2\end{bmatrix}
=\begin{bmatrix}-0.4\\0.4\end{bmatrix}.
$$

The first row gives $p'_1-p'_2=-1$. With zero mean, $p'_1+p'_2=0$, so $p'_1=-0.5$ and $p'_2=0.5$. The corrected face velocity is

$$
u=u^*-d_e\frac{p'_2-p'_1}{h}
=0.2-0.1\frac{0.5-(-0.5)}{0.5}=0.
$$

Thus the unrelaxed changes are $\Delta p_1=p'_1=-0.5$ and $\Delta p_2=p'_2=0.5$. Both corrected divergences are zero. A common constant added to $p'_1$ and $p'_2$ leaves this calculation unchanged.

**Pressure relaxation and velocity correction.** The pressure relaxation factor $\alpha_p$ is the fraction of $p'$ added to the pressure stored for the next momentum predictor: $p^{k+1}=p^k+\alpha_p p'$. The stored pressure change is therefore $\alpha_p p'$, rather than the full unrelaxed $\Delta p=p'$. If only $\alpha_p=0.3$ of the velocity correction were applied, the shared velocity would remain $0.2-0.3(0.2)=0.14$. The two mass defects would then be $+0.28$ and $-0.28$. With $\alpha_p=0.3$, the stored pressures become $-0.15$ and $0.15$ from the zero initial guess, while the fully corrected shared velocity remains zero. This velocity need not yet satisfy momentum with the relaxed stored pressure; the next predictor and correction continue the coupling iteration. The conservative velocity correction is applied fully.

**Local and global conservation.** The initial global sum was already $0.4-0.4=0$, but each cell was imbalanced. A zero total boundary flux alone cannot certify local continuity.

### 7 continued: Prepare a steady iteration: under-relaxation
A coupling *iteration* updates an estimate of a steady solution. The
counter $k$ labels those updates. It does not measure elapsed physical time.
The estimates entering the update are $q^k$ and $p^k$.

**Velocity under-relaxation.** Convection coefficients depend on velocity,
so replacing an estimate by a very different predictor can destabilize the
next coefficient update. An under-relaxation factor $\alpha_u$, with
$0<\alpha_u\leq1$, controls this change. Subscript $u$ refers to velocity;
the same factor is used for both components here.

Let $a_f^0$ be the center coefficient before relaxation. The superscript $0$
identifies the original coefficient of this assembly, not an initial time.
The relaxed row uses

$$
a_f^{\rm rel}=\frac{a_f^0}{\alpha_u},\qquad
b_f^{\rm rel}=b_f+
\left(\frac{1}{\alpha_u}-1\right)a_f^0q_f^k.
$$

The label $\mathrm{rel}$ means relaxed. Neighbor coefficients are unchanged.
The larger diagonal is accompanied by a known source containing the old
velocity estimate. At a converged fixed point the new and old velocities
coincide, so these extra diagonal and source terms cancel. The intended
steady momentum equation is preserved.

For the preceding single-row example, let $a_e^0=0.64$, the old estimate be
$u_e^k=0.02$, and choose $\alpha_u=0.7$. Holding its neighbor and pressure
contributions fixed gives

$$
\begin{aligned}
a_e^{\rm rel}&=0.64/0.7\simeq0.9142857,\\
\text{added source}&=(1/0.7-1)(0.64)(0.02)\simeq0.005485714,\\
u_e^*&\simeq(0.0152+0.008+0.005485714)/0.9142857=0.031375.
\end{aligned}
$$

For this frozen-row illustration, this is also
$0.7(0.03625)+0.3(0.02)$. In the coupled solver, relaxation is applied
to the assembled momentum equations as written above. The pressure correction
uses the relaxed reciprocal diagonal $d_f=1/a_f^{\rm rel}$.

**Pressure under-relaxation.** The separate factor $\alpha_p$, with
$0<\alpha_p\leq1$, controls the pressure stored for the next predictor:
$p^{k+1}=p^k+\alpha_p p'$. The full velocity correction is retained to satisfy
continuity, as the two-cell example demonstrated. The factors $\alpha_u$ and
$\alpha_p$ are numerical controls, not fluid properties.

In [3]:
# One frozen momentum row: use unrounded coefficients in the calculation.
import numpy as np
row_a = 0.64
row_neighbors = np.array([0.12, 0.20, 0.16, 0.16]) @ np.array([0.04, 0.02, 0.03, 0.01])
row_source = 0.0
row_pressure_gradient = (0.008 - 0.010) / 0.25
row_unrelaxed = (row_neighbors + row_source - row_pressure_gradient) / row_a
row_alpha = 0.7
row_old_velocity = 0.02
row_relaxed_a = row_a / row_alpha
row_relaxed_source = row_source + (1 / row_alpha - 1) * row_a * row_old_velocity
row_predictor = (row_neighbors + row_relaxed_source - row_pressure_gradient) / row_relaxed_a
print(f"Neighbor contributions: {row_neighbors:.6f}")
print(f"Original source b: {row_source:.6f}; relaxed source: {row_relaxed_source:.9f}")
print(f"Unrelaxed row velocity: {row_unrelaxed:.6f}; relaxed predictor: {row_predictor:.6f}")
assert np.isclose(row_unrelaxed, 0.03625)
assert np.isclose(row_predictor, 0.031375)
assert np.isclose(row_predictor, row_alpha * row_unrelaxed + (1-row_alpha) * row_old_velocity)
# Separate wall-face example: the distance to a prescribed lid is h/2.
wall_weight = 2 / (100 * 0.25**2)
wall_source = wall_weight * 1.0
print(f"Separate lid-face contribution: diagonal={wall_weight:.6f}, source={wall_source:.6f}")
assert np.isclose(wall_weight, 0.32) and np.isclose(wall_source, 0.32)

Neighbor contributions: 0.015200
Original source b: 0.000000; relaxed source: 0.005485714
Unrelaxed row velocity: 0.036250; relaxed predictor: 0.031375
Separate lid-face contribution: diagonal=0.320000, source=0.320000

### 7 continued: Decide whether both equations have been satisfied
A *residual* is the left side of an equation minus its right side,
evaluated using the current estimates. Zero residual means that discrete
equation is satisfied. The cell continuity residual is already
$r_{c,P}=(Dq)_P$.

For the momentum equations, collect their residuals into a column $r_m$:

$$
r_m=A(q)q-b+Gp.
$$

Here $A(q)$ means that convection coefficients are rebuilt from the current
velocity before evaluating this test. Use the original, unrelaxed steady
equations. This checks the physical discretization being solved rather than
only the temporary relaxed predictor equations.

To report one number for a residual column $r$, use the infinity norm

$$
\|r\|_\infty=\max_i|r_i|.
$$

Index $i$ runs through that column's entries; the operation selects the
largest absolute entry. Thus the two required checks are

$$
\|r_m\|_\infty<\varepsilon_m,\qquad
\|Dq\|_\infty<\varepsilon_c.
$$

The positive numbers $\varepsilon_m$ and $\varepsilon_c$ are the selected
momentum and continuity tolerances. They are separate because the residuals
test different equations. The comparison reports require momentum below $10^{-6}$ and divergence below
$10^{-9}$ as separate acceptance checks. The finite-volume code has one
`tolerance` setting for both of its native stopping tests: $10^{-7}$
in the baseline runs and $10^{-6}$ in the higher-Re study. The report-level
divergence check is stricter than those native thresholds; it is verified
from the returned fields, rather than selected through a separate solver knob.

A small change between successive velocities is insufficient: strong
under-relaxation can produce a small change even when the momentum balance
is still inaccurate. Small equation residuals are also distinct from small
spatial discretization error. Accuracy still requires the reference-profile
and mesh-refinement comparisons later in the lesson.

In a steady coupling iteration, both equation checks are evaluated after
the velocity and pressure updates, using the latest corrected fields.

### 8: SIMPLE: assemble the steady coupling iteration
SIMPLE means Semi-Implicit Method for Pressure-Linked Equations. It combines
the momentum solve, pressure correction and conservative velocity update
already derived. Begin iteration $k$ with velocity $q^k$ and pressure $p^k$.
For the cavity runs, the initial interior velocity and pressure are zero.
The moving lid and stationary walls remain prescribed boundary data; their
known contributions enter the momentum source $b$.



- **Build momentum.** Evaluate convection from $q^k$ and assemble
the original steady matrix $A$ and known source $b$. Apply the velocity
under-relaxation rule from Section 7 to obtain $A^{\rm rel}$ and $b^{\rm rel}$.
The relaxed center coefficients become the diagonal of $A^{\rm rel}$; its
neighbor entries are unchanged. The column $b^{\rm rel}$ collects the relaxed
source entries.

- **Predict velocity.** Solve the relaxed momentum equations using
the current pressure. The result is $q^*$, which may violate continuity.

- **Calculate the imbalance.** Apply $D$ to obtain one residual
$r_{c,P}^*$ per pressure cell. Use the relaxed inverse diagonal $d$ to build
the pressure matrix $L=-DdG$.

- **Solve pressure correction.** Solve $Lp'=-Dq^*$ with the wall
correction conditions and one pressure reference, as derived in Section 6.

- **Update the fields.** Apply the full face-velocity correction
and the under-relaxed pressure update shown below.

- **Test both equations.** Rebuild the unrelaxed momentum coefficients
from the corrected velocity and check the momentum and continuity tolerances.
If either fails, use the corrected fields as the next estimates and repeat.

In compact notation, the solve and updates are

$$
\begin{aligned}
A^{\rm rel}q^*&=b^{\rm rel}-Gp^k,\\
Lp'&=-Dq^*,\\
q^{k+1}&=q^*-dGp',\\
p^{k+1}&=p^k+\alpha_p p'.
\end{aligned}
$$

The stored pressure increment is $\alpha_p p'$, whereas the unrelaxed
correction is $\Delta p=p'$. Velocity receives its full correction so that
the cell balances are conservative. Prescribed wall velocities remain fixed;
a common pressure offset is removed without changing pressure gradients.

The retained baseline uses $\alpha_u=0.7$, $\alpha_p=0.3$,
a native solver tolerance of $10^{-7}$. These numerical controls
do not change the Reynolds number. This SIMPLE branch solves a steady
problem; increasing $k$ does not advance physical time.

### 8 continued: SIMPLE: follow the loop

![simple visual](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/simple_visual.png)

**Figure 8.** SIMPLE for a steady problem. Follow the blue boxes downward. The red return path rebuilds momentum after an unconverged iteration. Correct face velocities fully, relax pressure as specified, and test both momentum and cell continuity.

A return along the red arrow begins a new steady nonlinear iteration. Rebuild the convection coefficients from the latest velocity and check both momentum and continuity.

### 8 continued: A complete SIMPLE pass on the same two cells
Use the closed two-cell geometry of Section 7: one shared horizontal velocity
$u$, cell spacing $h=0.5$, and zero normal velocity at every external wall.
There is only one unknown velocity, so the column $q$ has just the entry $u$.
The two pressures are $p_1$ and $p_2$.

For this algebraic exercise, prescribe the original, volume-normalized momentum
row

$$
7u=2-\frac{p_2-p_1}{0.5}.
$$

Thus the unrelaxed center coefficient is $a^0=7$ and the known source is
$b=2$. These specified numbers isolate the coupling operations; they are not
a spatially resolved cavity calculation. Start from $u^0=0$ and
$p_1^0=p_2^0=0$, and select $\alpha_u=0.7$, $\alpha_p=0.3$.

**1. Relax the momentum row.** At the first pass, $k=0$:

$$
a^{\rm rel}=7/0.7=10,\qquad
b^{\rm rel}=2+(1/0.7-1)7u^0=2.
$$

**2. Solve the predictor.** The current pressure gradient is zero, so

$$
u^*=\frac{2-(0-0)/0.5}{10}=0.2,\qquad d=1/10=0.1.
$$

The values $u^*=0.2$ and $d=0.1$ used in Section 7 now follow from the same
momentum row and current estimates.

**3. Calculate the cell imbalances.** Positive $u^*$ leaves cell 1 and
enters cell 2:

$$
Dq^*=\begin{bmatrix}u^*/h\\-u^*/h\end{bmatrix}
=\begin{bmatrix}0.4\\-0.4\end{bmatrix}.
$$

**4. Solve the pressure correction.** Use the matrix from Section 7:

$$
0.4\begin{bmatrix}1&-1\\-1&1\end{bmatrix}
\begin{bmatrix}p'_1\\p'_2\end{bmatrix}
=\begin{bmatrix}-0.4\\0.4\end{bmatrix}.
$$

Its first row gives $p'_1-p'_2=-1$. Impose the zero-mean reference
$p'_1+p'_2=0$, giving $p'_1=-0.5$, $p'_2=0.5$. The second mass-balance row
then follows as well; it is dependent because the cells share their only
interior face and all external normal flow rates are zero.

### 8 continued: Correct both fields, then check the original equations
**5. Update velocity and stored pressure.** Apply the full face correction:

$$
u^1=u^*-d\frac{p'_2-p'_1}{h}
=0.2-0.1\frac{0.5-(-0.5)}{0.5}=0.
$$

Store the under-relaxed pressure for the next predictor:

$$
p_1^1=0+0.3(-0.5)=-0.15,\qquad
p_2^1=0+0.3(0.5)=0.15.
$$

The superscript 1 means one completed steady coupling pass, not a physical
time step. Both cell continuity residuals are now zero.

**6. Check momentum using the original row.** Its scalar residual is

$$
r_m=7u-b+\frac{p_2-p_1}{h}.
$$

For the updated fields this is

$$
r_m^1=7(0)-2+\frac{0.15-(-0.15)}{0.5}=-1.4.
$$

The original momentum equation is not yet satisfied with the stored pressure,
even though continuity is exact. This is why the next SIMPLE pass is needed.

At pass 2, use $u^1=0$ and $p^1=(-0.15,0.15)$ as inputs. The relaxed source
remains 2, and

$$
u^*=\frac{2-0.30/0.5}{10}=0.14.
$$

The next pressure correction is $p'=(-0.35,0.35)$. Correcting velocity fully
again gives zero; storing $0.3p'$ gives $p^2=(-0.255,0.255)$ and
$r_m^2=-0.98$. Repeating the same operations gives:

| Completed pass | $u^*$ | Corrected $u$ | Stored $(p_1,p_2)$ | $\vertr_m\vert$ |
| --- | --- | --- | --- | --- |
| 1 | 0.200 | 0 | $(-0.150,0.150)$ | 1.400 |
| 2 | 0.140 | 0 | $(-0.255,0.255)$ | 0.980 |
| 3 | 0.098 | 0 | $(-0.3285,0.3285)$ | 0.686 |

The exact constrained steady solution is $u=0$, $p_1=-0.5$, $p_2=0.5$.
This one-velocity example has no off-diagonal velocity coupling, so its
diagonal pressure-response approximation is exact for a frozen row.
The chosen pressure under-relaxation makes the stored pressures approach
the solution over successive passes. Real cavity rows also contain neighbor
coupling and velocity-dependent convection coefficients.

In [4]:
# Prescribed two-cell algebra, not a resolved cavity simulation.
import numpy as np
import pandas as pd

def simple_two_cell_walkthrough(passes=3):
    h, a_original, b_known = 0.5, 7.0, 2.0
    alpha_u, alpha_p = 0.7, 0.3
    u, p = 0.0, np.zeros(2)
    D = np.array([[1 / h], [-1 / h]])
    G = np.array([[-1 / h, 1 / h]])
    trace = []
    for completed_pass in range(1, passes + 1):
        a_relaxed = a_original / alpha_u
        b_relaxed = b_known + (1 / alpha_u - 1) * a_original * u
        u_star = (b_relaxed - (G @ p).item()) / a_relaxed
        d = 1 / a_relaxed
        imbalance = D @ np.array([u_star])
        L = -(D @ (d * G))
        # Use one mass row and the zero-mean pressure condition.
        # The other mass row is dependent for these two closed cells.
        gauge_system = np.vstack([L[0], np.ones(2)])
        p_prime = np.linalg.solve(gauge_system, [-imbalance[0], 0.0])
        np.testing.assert_allclose(L @ p_prime, -imbalance, atol=1e-14)
        u = u_star - d * (G @ p_prime).item()
        p = p + alpha_p * p_prime
        momentum = a_original * u - b_known + (G @ p).item()
        continuity = np.max(np.abs(D @ np.array([u])))
        trace.append({'pass': completed_pass, 'u*': u_star,
            "p1'": p_prime[0], "p2'": p_prime[1], 'u_next': u,
            'p1_stored': p[0], 'p2_stored': p[1],
            'original momentum residual': momentum,
            'continuity Linf': continuity})
    return pd.DataFrame(trace)

simple_trace = simple_two_cell_walkthrough()
display(simple_trace.round(6))
np.testing.assert_allclose(simple_trace['u*'], [0.2, 0.14, 0.098], atol=1e-14)
np.testing.assert_allclose(simple_trace['p2_stored'], [0.15, 0.255, 0.3285], atol=1e-14)
np.testing.assert_allclose(simple_trace['original momentum residual'], [-1.4, -0.98, -0.686], atol=1e-14)
assert simple_trace['continuity Linf'].max() < 1e-14
print('Continuity is satisfied at each corrected state; stored pressure still requires iteration.')

Continuity is satisfied at each corrected state; stored pressure still requires iteration.

   pass     u*    p1'  ...  p2_stored  original momentum residual  continuity Linf
0     1  0.200 -0.500  ...     0.1500                      -1.400              0.0
1     2  0.140 -0.350  ...     0.2550                      -0.980              0.0
2     3  0.098 -0.245  ...     0.3285                      -0.686              0.0

[3 rows x 9 columns]

### 9: Physical time and backward-Euler momentum
PISO and PIMPLE solve a transient momentum equation. Superscripts $n$ and $n+1$ denote physical time levels, separated by $\Delta t$. For one face velocity,

$$
\left.\frac{\partial q_f}{\partial t}\right|_{n+1}
\approx\frac{q_f^{n+1}-q_f^n}{\Delta t}.
$$

If the spatial momentum row has center coefficient $a_f^{\rm space}$ and source $b_f^{\rm space}$, backward Euler produces

$$
\begin{aligned}
\left(a_f^{\rm space}+\frac{1}{\Delta t}\right)q_f^{n+1}
&=\sum_g a_{fg}q_g^{n+1}+b_f^{\rm space}
+\frac{q_f^n}{\Delta t}-(Gp^{n+1})_f.
\end{aligned}
$$

Thus the transient assembly adds $1/\Delta t$ to the diagonal and the known old velocity $q_f^n/\Delta t$ to the source.

**Old-time velocity is fixed.** At the beginning of the physical step, store $q^n$. Every momentum assembly and every correction within that step uses the same old-time source. Replacing $q^n$ with an intermediate corrected velocity would change the discrete physical problem.

**Nonlinear coefficients.** Convective coefficients depend on advecting velocity. They must be evaluated from a known estimate to form a linear predictor system. Such coefficients are called frozen or lagged during that solve. A perfectly solved linear predictor can still differ from the fully implicit nonlinear step if its coefficients were evaluated at an outdated velocity.

**Three iteration levels.** A linear solver solves one matrix equation. A pressure corrector couples pressure and velocity for a frozen momentum matrix. An outer corrector rebuilds that matrix using the latest velocity. None of these is an additional physical time advance.

Backward Euler is first-order accurate in time. Extra correctors can reduce algebraic coupling error, but do not change its time-discretization order. A larger stable $\Delta t$ still requires a temporal-accuracy assessment.

### Keep the accepted old-time field fixed

At the start of a physical step, store the accepted velocity $q^n$ at time $t^n$.
The backward-Euler source $q^n/\Delta t$ uses that same stored field throughout
the step. The provisional and corrected new-time estimates can change without
changing $q^n$. Replace the accepted old-time field only when advancing to the
next physical step. The following PISO and PIMPLE sections specify their
correction counters separately from the physical-time index $n$.

### Reading the correction coefficient in an integrated equation

Let $V_e$ be the horizontal-velocity control-volume size and $a_e$ the momentum
diagonal **after** division by $V_e$. The integrated row therefore has diagonal
$V_e a_e$. With the dimensionless pressure used here, the local SIMPLE correction is

$$
(V_e a_e)u'_e=-V_e\frac{p'_E-p'_P}{h}.
$$

$p'_E$ and $p'_P$ are the pressure corrections in adjacent pressure cells;
$h$ is their center-to-center distance. Dividing the momentum row by $V_e$ gives

$$
a_eu'_e=-\frac{p'_E-p'_P}{h},\qquad
d_e=\frac{V_e}{V_e a_e}=\frac{1}{a_e},\qquad
u'_e=-d_e\frac{p'_E-p'_P}{h}.
$$

Thus “volume divided by diagonal” and the code's “reciprocal diagonal” agree
when applied to the corresponding integrated and normalized rows. For
dimensional pressure, acceleration uses $p_d/\rho$; $\rho$ is density. The
matrix $D$ in the lesson denotes divergence, while $d_e$ is this face's
correction sensitivity. Pressure under-relaxation changes the stored pressure
update; the conservative face-velocity correction is still applied fully.

### 10: PISO: several corrections in one physical time step
PISO means Pressure-Implicit with Splitting of Operators. Start with the
accepted old-time velocity $q^n$ and pressure $p^n$. The next accepted fields
will belong to time $n+1$, one physical interval $\Delta t$ later.

First assemble the transient momentum equation from Section 9 and solve

$$
Aq^*=b-Gp^{\rm guess}.
$$

The pressure $p^{\rm guess}$ is the initial pressure estimate for this step,
normally the preceding accepted pressure. The source $b$ includes the fixed
old-time contribution $q^n/\Delta t$ and known wall contributions. The
predictor $q^*$ satisfies this momentum solve, but can still violate continuity.
Convection coefficients are evaluated from the initial velocity estimate,
for example $q^n$, and held fixed during the following inner corrections.

The next operations improve pressure and velocity within this same step.
Write $q^{(0)}=q^*$ and use $m$ to count inner corrections. Parenthesized
superscripts identify a correction estimate, not a physical time or a power.

| Quantity | Behavior during this PISO loop |
| --- | --- |
| $q^n$ | Accepted old-time velocity; fixed throughout the step. |
| $A,b$ | Transient momentum coefficients and source; assembled once. |
| $d,R$ | Reciprocal diagonal and off-diagonal part of this same $A$; fixed. |
| $L=-DdG$ | Pressure matrix from the fixed reciprocal diagonal; fixed. |
| $q^{(m)},p^{(m)}$ | Current estimates at the new time level; updated by corrections. |
| $H^{(m)}$ | Known source plus the latest neighbor-velocity contributions; recomputed. |

The key distinction is between a fixed momentum matrix and changing velocity
values within it. Updating the neighbor contributions is what makes another
pressure correction different from solving an identical equation again.

### 10 continued: Form each inner pressure solve and velocity update
Given the current estimate $q^{(m)}$, collect its neighbor contributions:

$$
H^{(m)}=b-Rq^{(m)}.
$$

The momentum-row reconstruction for a new pressure estimate is

$$
q^{(m+1)}=d[H^{(m)}-Gp^{(m+1)}].
$$

Require its cell divergence to vanish. Applying $D$ gives

$$
\begin{aligned}
0&=D(dH^{(m)})-DdG p^{(m+1)},\\
Lp^{(m+1)}&=-D(dH^{(m)}),\qquad L=-DdG.
\end{aligned}
$$

Thus one inner correction consists of recomputing $H^{(m)}$, solving this
pressure equation and reconstructing all face velocities. The next
correction repeats these operations with the newly reconstructed velocity.

**Full pressure or increment?** In this implementation,
$p^{(m+1)}$ is the full pressure field in the selected reference convention.
It replaces the previous pressure estimate. It is not SIMPLE's additive
correction $p'$, and must not be added to the previous pressure.

Let $N_i$ denote the chosen number of inner corrections. After those
corrections, accept $q^{n+1}=q^{(N_i)}$ and $p^{n+1}=p^{(N_i)}$.
Only this acceptance advances the physical time. The retained baseline uses
$N_i=2$ and does not apply SIMPLE's under-relaxation in this transient branch.

The convection coefficients remain those assembled for the predictor.
Further inner corrections improve coupling for that fixed matrix. They do
not rebuild convection from the latest new-time velocity; PIMPLE adds an
outer iteration for that purpose.

### 10 continued: PISO: follow the loop

![piso visual](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/piso_visual.png)

**Figure 9.** PISO within one physical time step. The red return path updates correction terms before another pressure solve, using fixed momentum coefficients. The saved old-time velocity remains unchanged until the new time level is accepted.

All inner corrections remain at the same new time level. The old-time velocity in the transient term is fixed. Each further pressure correction uses updated velocity information; an unchanged repeated pressure solve is not an additional PISO correction.

### 11: PISO: a frozen-matrix numerical example
This reduced two-velocity system illustrates coupling algebra; it is not a cavity grid. Let

$$
A=\begin{bmatrix}4&1\\1&3\end{bmatrix},\quad
b=\begin{bmatrix}2\\0\end{bmatrix},\quad
D=\begin{bmatrix}1&-1\end{bmatrix},\quad
G=\begin{bmatrix}-1\\1\end{bmatrix}.
$$

Here $p$ is one independent scalar pressure variable after removing an arbitrary common pressure offset. It is not a separate pressure value in each physical cell. The matrices are prescribed to illustrate coupling algebra; they are not derived from the earlier two-cell geometry. Continuity is $Dq=q_1-q_2=0$. From $A$,

$$
d=\begin{bmatrix}1/4&0\\0&1/3\end{bmatrix},\quad
R=\begin{bmatrix}0&1\\1&0\end{bmatrix},\quad L=-DdG=7/12.
$$

Starting from $p^{\rm guess}=0$, the momentum predictor solves $Aq^*=b$:

$$
q^*=\begin{bmatrix}6/11\\-2/11\end{bmatrix},\qquad Dq^*=8/11.
$$

It satisfies momentum exactly but violates continuity. The first inner correction uses

$$
H^{(0)}=b-Rq^*=\begin{bmatrix}24/11\\-6/11\end{bmatrix},\qquad
dH^{(0)}=\begin{bmatrix}6/11\\-2/11\end{bmatrix}.
$$

Solve pressure and reconstruct velocity:

$$
\begin{aligned}
\frac{7}{12}p^{(1)}&=-D(dH^{(0)})=-\frac{8}{11},&p^{(1)}&=-\frac{96}{77},\\
q_1^{(1)}&=\frac14\left(\frac{24}{11}+p^{(1)}\right)=\frac{18}{77},&
q_2^{(1)}&=\frac13\left(-\frac{6}{11}-p^{(1)}\right)=\frac{18}{77}.
\end{aligned}
$$

The signs in these two velocity formulas follow from $G=(-1,1)^T$. Now $Dq^{(1)}=0$. Nevertheless, substituting these fields into the original frozen momentum equation gives

$$
r^{(1)}=Aq^{(1)}-b+Gp^{(1)}
=\begin{bmatrix}32/77\\-24/77\end{bmatrix}.
$$

The vector $r=Aq-b+Gp$ is the error in satisfying the momentum rows; exact satisfaction gives $r=0$. Its infinity norm is the largest absolute entry, $\|r\|_\infty=\max_i|r_i|$, where $i$ labels a momentum row. Mass balance is exact here, but momentum consistency still needs improvement.

### 11 continued: The second pressure correction
The corrected neighbor velocities change $H$, even though $A$ and $L$ are unchanged:

$$
H^{(1)}=b-Rq^{(1)}=\begin{bmatrix}136/77\\-18/77\end{bmatrix},\qquad
dH^{(1)}=\begin{bmatrix}34/77\\-6/77\end{bmatrix}.
$$

The next pressure and velocity are

$$
\begin{aligned}
\frac{7}{12}p^{(2)}&=-\frac{40}{77},&p^{(2)}&=-\frac{480}{539},\\
q^{(2)}&=d\left[H^{(1)}-Gp^{(2)}\right]
=\begin{bmatrix}118/539\\118/539\end{bmatrix}.
\end{aligned}
$$

The pressure is replaced by $p^{(2)}$; adding $p^{(2)}$ to $p^{(1)}$ would be incorrect. Again continuity is exact. The remaining frozen-momentum defect is

$$
r^{(2)}=\begin{bmatrix}-8/539\\-8/539\end{bmatrix}.
$$

| Stage | $\vertDq\vert$ | $\VertAq-b+Gp\Vert_\infty$ |
| --- | --- | --- |
| Momentum predictor | $8/11$ | $0$ |
| Inner correction 1 | $0$ | $32/77\approx0.41558$ |
| Inner correction 2 | $0$ | $8/539\approx0.01484$ |

The exact constrained solution is $q_1=q_2=2/9$ and $p=-8/9$. It follows by imposing $q_1=q_2=s$ in both original momentum rows: $5s-p=2$ and $4s+p=0$, hence $9s=2$.

The second correction reduces momentum inconsistency in this example while preserving mass balance. This is a demonstrated property of these specified matrices, not a guarantee of monotone convergence for every CFD system.

The right-hand side of the pressure equation changes from $-8/11$ to $-40/77$. The example therefore distinguishes another PISO correction from another iteration of an unchanged linear pressure solve.

### 12: PIMPLE: outer coefficient updates and inner corrections
PIMPLE combines an outer momentum-update loop with PISO inner corrections. Physical time levels are $n,n+1$; $\ell$ labels outer updates and $m$ labels inner pressure corrections. The previous physical velocity $q^n$ is stored once.

Before writing the nested equations, distinguish their labels and stored fields:

| Label or field | Meaning |
| --- | --- |
| $n,n+1$ | Old and new physical time levels. |
| $\ell$ | Outer pass: rebuild momentum coefficients using the latest velocity estimate. |
| $m$ | Inner correction within one outer pass: update pressure and face velocity. |
| $q^n$ | Accepted old-time velocity, saved once and kept fixed. |
| $q_{\rm lag}^{(\ell)},p_{\rm lag}^{(\ell)}$ | Velocity and pressure estimates entering outer pass $\ell$. The subscript lag identifies inputs carried from the preceding pass. |
| $q^{(\ell,0)}$ | Momentum predictor at the start of outer pass $\ell$. |
| $q^{(\ell,m)}$ | New-time velocity estimate after $m$ inner corrections in pass $\ell$. |

For example, $(\ell,m)=(2,1)$ means the first inner correction of the second
outer pass. It remains within the same physical step. The first outer pass
starts from the accepted old-time fields; subsequent passes start from the
latest corrected new-time fields.

### 12 continued: Assemble an outer pass and carry its fields forward
At the start of outer pass $\ell$, assemble convection using the latest available corrected velocity $q_{\rm lag}^{(\ell)}$. Here $A_{\rm space}$ contains the spatial convection and diffusion coefficients,
$b_{\rm wall}$ contains prescribed wall contributions, and $I$ is the identity
matrix (ones on its diagonal, zeros elsewhere). Adding the backward-Euler terms gives

$$
A^{(\ell)}=A_{\rm space}(q_{\rm lag}^{(\ell)})+I/\Delta t,
\qquad b^{(\ell)}=b_{\rm wall}^{(\ell)}+q^n/\Delta t.
$$

The same $q^n$ appears in every outer pass. For this fixed-grid, fixed-lid code, the wall source is constant, so $b^{(\ell)}$ has the same value in every outer pass. The prescribed wall motion and old-time source belong to the same physical step.

The first outer pass starts from $q^n,p^n$. The symbol $p_{\rm lag}^{(\ell)}$ denotes the latest available pressure at the start of outer pass $\ell$. A new momentum predictor is solved using that pressure. The predictor is therefore

$$
A^{(\ell)}q^{(\ell,0)}=b^{(\ell)}-Gp_{\rm lag}^{(\ell)}.
$$

### 12 continued: Inner corrections and the next outer pass
From this assembly define $d^{(\ell)}$ as its reciprocal diagonal, $R^{(\ell)}$ as its off-diagonal part, and $L^{(\ell)}=-D d^{(\ell)}G$ as its pressure matrix. These three objects are fixed during the inner corrections of outer pass $\ell$:

$$
\begin{aligned}
H^{(\ell,m)}&=b^{(\ell)}-R^{(\ell)}q^{(\ell,m)},\\
L^{(\ell)}p^{(\ell,m+1)}&=-D\left(d^{(\ell)}H^{(\ell,m)}\right),\\
q^{(\ell,m+1)}&=d^{(\ell)}\left[H^{(\ell,m)}-Gp^{(\ell,m+1)}\right].
\end{aligned}
$$

With $N_i$ inner corrections per outer pass, the initial and transfer rules are

$$
\begin{aligned}
q_{\rm lag}^{(1)}&=q^n,&p_{\rm lag}^{(1)}&=p^n,\\
q_{\rm lag}^{(\ell+1)}&=q^{(\ell,N_i)},&p_{\rm lag}^{(\ell+1)}&=p^{(\ell,N_i)}.
\end{aligned}
$$

Thus the final corrected fields of one outer pass initialize the next. Rebuilding $A$ also rebuilds $d$, $R$ and $L$. Each inner solve computes the full pressure field in the chosen gauge, as in this PISO implementation.

**Two different purposes.** Inner corrections improve pressure-velocity consistency for the current matrix. Outer passes update the nonlinear coefficients that matrix represents. Neither loop advances physical time. Only after the final outer pass are the accepted fields assigned to time $n+1$.

With one outer pass, this code reduces to its PISO algorithm. Its PIMPLE branch does not apply SIMPLE's under-relaxation. The retained code performs the configured number of outer and inner corrections, then tests steady convergence between completed steps. A transient-accuracy study must also assess the time step and remaining within-step defects. Additional loops reduce certain algebraic errors at extra cost; they do not increase backward-Euler's formal time order.

### 12 continued: PIMPLE: follow the loop

![pimple visual](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/pimple_visual.png)

**Figure 10.** PIMPLE within one physical time step. Green: inner pressure-velocity corrections with fixed momentum coefficients. Red: outer passes rebuild those coefficients from the latest new-time estimate. The retained code completes the configured passes, accepts the step, and tests steady convergence between steps. Neither correction loop advances the saved old-time data.

The outer loop updates convection coefficients and resolves momentum. The inner loop updates pressure and face velocity for those coefficients. Neither loop advances physical time. The retained code completes the configured passes and checks steady convergence between steps. A time-accurate simulation also needs within-step and time-step accuracy checks.

### 13: PIMPLE: a nonlinear coefficient example
Extend the preceding algebraic example by making its momentum coefficients depend on velocity:

$$
A(s)=\begin{bmatrix}4+s&1\\1&3+s\end{bmatrix},\qquad
s=(q_1+q_2)/2,\qquad b=\begin{bmatrix}2\\0\end{bmatrix}.
$$

Keep the same $D,G$ and initial $q=0,p=0$. At each outer pass, evaluate $s$ from its starting velocity, freeze $A(s)$, solve a new predictor, and perform two inner corrections. The source $b$ remains fixed. This toy coefficient law illustrates lagging; it is not a Navier-Stokes convection discretization.

At outer pass 1, $s=0$, so the two inner corrections are exactly the previous PISO example. They end at $q_1=q_2=0.2189239332$. The next outer pass uses

$$
A^{(2)}=\begin{bmatrix}4.2189239332&1\\1&3.2189239332\end{bmatrix},
$$

and recomputes $d,R,L$ before the new predictor and inner corrections.



| Outer pass | Frozen $s$ | Final $q_1=q_2$ | Final $p$ | Nonlinear defect |
| --- | --- | --- | --- | --- |
| 1 | $0$ | $0.2189239332$ | $-0.8905380334$ | $3.30854\times10^{-2}$ |
| 2 | $0.2189239332$ | $0.2119026446$ | $-0.8940486777$ | $1.53537\times10^{-3}$ |
| 3 | $0.2119026446$ | $0.2122289655$ | $-0.8938855173$ | $7.14784\times10^{-5}$ |

The reported defect is the largest absolute component of the nonlinear momentum residual, evaluated with coefficients rebuilt from the final velocity:

$$
\left\|A\left((q_1+q_2)/2\right)q-b+Gp\right\|_\infty.
$$

It is different from the residual of the frozen predictor matrix. All final mass defects are below $10^{-15}$.

For a constrained fixed point, set $q_1=q_2=s$ and add the two momentum rows:

$$
(9+2s)s=2,\qquad
s_{\pm}=\frac{-9\pm\sqrt{97}}4,\qquad p=s/2-1.
$$

Both roots satisfy the constrained quadratic. The iteration initialized at
$q=0,p=0$ follows the positive branch $s_+=0.2122144504$ shown in the table.
The other root is $s_-=-4.7122144504$ and has negative diagonal entries in
this toy matrix. The displayed iteration does not assert global uniqueness
of the nonlinear algebraic system.

The table shows the benefit of coefficient updates for this example. Actual cavity efficiency must be judged using its own measured equation defects, accuracy and solve costs.

In [3]:
# Reduced algebraic examples, not cavity-flow measurements.
D = np.array([[1., -1.]])
G = -D.T
b = np.array([2., 0.])

def inner_corrections(A, pressure_guess, count=2):
    d = np.diag(1. / np.diag(A))
    R = A - np.diag(np.diag(A))
    L = -D @ d @ G
    q = np.linalg.solve(A, b - G[:, 0] * pressure_guess)
    records = [{"stage": "predictor", "q1": q[0], "q2": q[1],
                "pressure": pressure_guess, "mass defect": abs((D @ q)[0]),
                "frozen momentum defect": np.max(np.abs(A @ q - b + G[:, 0] * pressure_guess))}]
    for inner in range(count):
        H = b - R @ q
        pressure = np.linalg.solve(L, -D @ (d @ H))[0]
        q = d @ (H - G[:, 0] * pressure)
        records.append({"stage": f"inner {inner+1}", "q1": q[0], "q2": q[1],
                        "pressure": pressure, "mass defect": abs((D @ q)[0]),
                        "frozen momentum defect": np.max(np.abs(A @ q - b + G[:, 0] * pressure))})
    return q, pressure, records

A = np.array([[4., 1.], [1., 3.]])
_, _, piso_example = inner_corrections(A, 0.)
display(pd.DataFrame(piso_example))

q = np.zeros(2)
pressure = 0.
pimple_example = []
for outer in range(3):
    frozen_s = q.mean()
    A = np.array([[4.+frozen_s, 1.], [1., 3.+frozen_s]])
    q, pressure, _ = inner_corrections(A, pressure, count=2)
    final_s = q.mean()
    A_final = np.array([[4.+final_s, 1.], [1., 3.+final_s]])
    nonlinear_defect = np.max(np.abs(A_final @ q - b + G[:, 0] * pressure))
    pimple_example.append({"outer": outer+1, "frozen s": frozen_s, "final q1": q[0],
                           "final q2": q[1], "pressure": pressure,
                           "nonlinear momentum defect": nonlinear_defect,
                           "mass defect": abs((D @ q)[0])})
display(pd.DataFrame(pimple_example))
exact_s = (np.sqrt(97.)-9.) / 4.
print("Exact nonlinear q1=q2:", exact_s, "; pressure:", exact_s/2.-1.)

,stage,q1,q2,pressure,mass defect,frozen momentum defect
0,predictor,0.545455,-0.181818,0.000000,7.272727e-01,2.220446e-16
1,inner 1,0.233766,0.233766,-1.246753,2.775558e-17,4.155844e-01
2,inner 2,0.218924,0.218924,-0.890538,0.000000e+00,1.484230e-02

,outer,frozen s,final q1,final q2,pressure,nonlinear momentum defect,mass defect
0,1,0.000000,0.218924,0.218924,-0.890538,0.033085,0.000000e+00
1,2,0.218924,0.211903,0.211903,-0.894049,0.001535,5.551115e-17
2,3,0.211903,0.212229,0.212229,-0.893886,0.000071,8.326673e-17

Exact nonlinear q1=q2: 0.21221445044902598 ; pressure: -0.893892774775487

### 14: Algorithm loops and computational work

![loop map](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/loop_map.png)

**Figure 11.** Comparison of repeated work. A SIMPLE cycle is a steady nonlinear iteration. PISO repeats pressure-velocity corrections within one step. PIMPLE nests those corrections inside momentum-coefficient updates. The red arrows denote repetition; they do not denote physical time advancement.

The nested loops act on one target problem at the current physical step. The diagram distinguishes steady SIMPLE iterations from PISO and PIMPLE time integration.

Let $N_i$ be the number of pressure correctors and $N_o$ the number of outer correctors. Each predictor solves horizontal and vertical momentum separately.

| Work unit | SIMPLE iteration | PISO step | PIMPLE step |
| --- | --- | --- | --- |
| Momentum assemblies | $1$ | $1$ | $N_o$ |
| Component momentum solves | $2$ | $2$ | $2N_o$ |
| Pressure solves | $1$ | $N_i$ | $N_oN_i$ |
| Physical time advances | $0$ | $1$ | $1$ |

For three outer and two inner correctors, PIMPLE uses three assemblies, six component momentum solves and six pressure solves per physical step. A direct linear solver may factor a pressure matrix once and reuse it within an inner loop, while solving different right-hand sides.

An iteration count alone cannot compare these costs. The retained runs use fixed corrector counts, rather than an adaptive inner tolerance. A steady stopping test is applied outside these operations.

### 15: Convergence, accuracy and the meaning of a residual
**Cell continuity.** The mass-balance diagnostic is $\max_P|r_{c,P}|$: the largest absolute continuity residual among all pressure cells. It is evaluated from face velocities, not from an interpolated picture of cell-center velocity.

**Momentum defect.** For a steady target, the implementation rebuilds the unrelaxed spatial coefficients using final velocity and evaluates the original momentum equations. For a transient step, a nonlinear step defect includes the same fixed old-time source:

$$
r_{\rm step}=A_{\rm space}(q^{n+1})q^{n+1}-b_{\rm wall}
+\frac{q^{n+1}-q^n}{\Delta t}+Gp^{n+1}.
$$

Small mass defect alone does not make this vector small, as the PISO numerical example demonstrated.

**Accuracy.** Agreement with independent reference velocities and stability under spatial refinement address solution accuracy. Ghia centerline tables validate selected velocity profiles; they do not validate pressure. A converged coarse-grid calculation can still be inaccurate.

**Transient accuracy.** Corrector loops reduce algebraic errors inside a step. Temporal error is assessed separately by reducing $\Delta t$ and comparing at matched physical times. Steady cavity agreement alone does not validate startup or oscillatory flow.

**Streamfunction-vorticity comparison.** Week 1 advances vorticity and solves streamfunction. Its native update norm is different from the finite-volume momentum defect. Their convergence histories use separate axes; common velocity errors and wall-clock times provide cross-formulation comparisons. $N$ finite-volume cells correspond to $N+1$ finite-difference nodes at matching spacing $h=1/N$.

**Higher Reynolds numbers.** Stronger convection and thinner layers can require more cells and more work. More pressure corrections cannot recover spatial structures missing from the mesh. Refinement and higher-$Re$ runs can take substantially longer and need more memory; the supplied coarse cases are the starting point for laptop or Colab use.

## 2.18 Further reading

- [Patankar (1980), Numerical Heat Transfer and Fluid Flow](https://www.routledge.com/Numerical-Heat-Transfer-and-Fluid-Flow/Patankar/p/book/9780891165224): staggered grids and SIMPLE.
- [Versteeg and Malalasekera (2007), An Introduction to Computational Fluid Dynamics](https://www.pearson.com/en-gb/subject-catalog/p/Versteeg-An-Introduction-to-Computational-Fluid-Dynamics-The-Finite-Volume-Method-2nd-Edition/P200000005670?view=educator): finite-volume transport and pressure correction.
- [Ferziger, Peric and Street (2020), Computational Methods for Fluid Dynamics](https://doi.org/10.1007/978-3-319-99693-6): incompressible-flow methods and errors.
- [Moukalled, Mangani and Darwish (2016), Chapter 15](https://doi.org/10.1007/978-3-319-16874-6_15): incompressible finite-volume coupling.
- [Issa (1986), original PISO paper](https://doi.org/10.1016/0021-9991(86)90099-9).
- [Official OpenFOAM algorithm controls](https://doc.cfd.direct/openfoam/user-guide-v13/fvsolution): pressure reference, inner and outer correctors.

The equations above specify this notebook's staggered-grid implementation. Collocated-grid interpolation and Rhie-Chow stabilization are separate topics.

## Recorded cavity evidence

All four formulations are included. The following tables distinguish reference-profile error, equation defects and recorded solver-call time. Matching spacing does not make the FV and FD spatial equations identical.

### How the benchmark errors are measured

Let $s_j$ denote an actual Ghia reference position, $f_{\rm ref,j}$ its tabulated
velocity and $f_{\rm num}(s_j)$ the computed profile interpolated linearly to
that position. The profile component $f$ is either horizontal or vertical velocity.

$$
E_{{\rm rel},2}=\frac{\sqrt{\sum_j[f_{\rm num}(s_j)-f_{\rm ref,j}]^2}}
{\sqrt{\sum_j f_{\rm ref,j}^{\,2}}},\qquad
E_\infty=\max_j|f_{\rm num}(s_j)-f_{\rm ref,j}|.
$$

Percentage error is $100E_{{\rm rel},2}$. These compare with independent velocity
samples; momentum and divergence residuals instead measure satisfaction of the
discrete equations. The qualified Re=400 vertical-velocity ($v$) profile score omits the
separately marked published point at $x/L=0.9063$; the all-point result is retained.
Axis labels such as $u/U$ denote the dimensional ratios used in the original
nondimensionalization. Stored values already represent those ratios.
Recorded seconds belong to a specified solver call and host; compare accuracy,
spacing and stopping definitions before comparing cost.

In [5]:
summary = pd.DataFrame([{
    "method": LABELS[r["config"]["method"]], "cells/side": r["config"]["cells"],
    "iterations/steps": r.get("iterations",r.get("steps")), "CPU seconds": r["runtime_seconds"],
    "Ghia u rel L2": r["ghia_u_relative_l2"], "Ghia v rel L2": r["ghia_v_relative_l2"],
    "FV momentum Linf": r.get("momentum_residual_linf",np.nan),
    "FV divergence Linf": r.get("continuity_linf",np.nan),
    "converged": r["converged"]} for r in recorded])
display(summary)

                      method  cells/side  ...  FV divergence Linf  converged
0                     SIMPLE          32  ...        3.219647e-15       True
1       PISO (2 corrections)          32  ...        1.933263e-14       True
2  PIMPLE (3 outer, 2 inner)          32  ...        2.126424e-14       True
3   Streamfunction-vorticity          32  ...                 NaN       True
4                     SIMPLE          64  ...        5.338611e-14       True
5       PISO (2 corrections)          64  ...        2.842171e-14       True
6  PIMPLE (3 outer, 2 inner)          64  ...        1.776357e-14       True
7   Streamfunction-vorticity          64  ...                 NaN       True

[8 rows x 9 columns]

### Retained Re=100 fields and histories

![profiles re100](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/profiles_re100.png)

**Figure 12.** Retained Re=100 centerline velocities at matched spacing h=1/64. Curves show all four formulations; black markers are Ghia et al. (1982) samples. FV uses 64 pressure cells per side and FD uses 65 boundary-inclusive nodes. Line styles and colors identify the computed series.

![field speed re100](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_speed_re100.png)

**Figure 13.** Retained Re=100 speed and velocity streamlines at h=1/64. All panels use the same physical color limits. Streamline arrows show circulation direction; their density does not measure vorticity.

![field omega re100](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_omega_re100.png)

**Figure 14.** Retained Re=100 signed vorticity with velocity streamlines at h=1/64. One symmetric logarithmic color scale is shared by all panels, linear for absolute vorticity up to 1. The displayed colorbar values are nondimensional physical vorticity, including wall peaks.

![field p re100](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_p_re100.png)

**Figure 15.** Retained Re=100 zero-mean pressure and velocity streamlines at h=1/64. One symmetric logarithmic color scale is shared, linear for absolute pressure up to 0.01. FD pressure is reconstructed after the vorticity solve. No independent pressure benchmark is claimed.

![convergence re100](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/convergence_re100.png)

**Figure 16.** Retained Re=100 finite-volume convergence histories at h=1/64. The horizontal coordinate is recorded solver-call wall time from one local run per method. Momentum and continuity are separate defects. The streamfunction-vorticity solver uses a different native stopping norm and is included in the adjacent timing tables, not on these FV residual axes.

## Run selected FV methods again

`RUN_NEW=False` loads retained results. Set it to `True` to compute one or all
three FV methods. The independent FD reference remains retained; a retained peer
appears only where matching spacing is available. Each new plot labels fresh
and retained cases separately.

The controls below map to the preceding equations: `velocity_relaxation` and
`pressure_relaxation` are SIMPLE's alpha factors; `pressure_correctors` is PISO/PIMPLE's
inner count; `outer_correctors` is PIMPLE's outer count. Relaxation settings are
ignored by this transient PISO/PIMPLE implementation, outer count is ignored
outside PIMPLE, and `dt` is ignored by steady SIMPLE. A new output folder preserves
each run's exact configuration and fields. Compare runtimes on the same host.

In [ ]:
from IPython.display import Markdown
from datetime import datetime, timezone
from uuid import uuid4
import hashlib, json

RUN_NEW = False
METHOD = "all"  # all three FV methods, or simple / piso / pimple
CELLS = 32
BASE_DT = 0.05                 # PISO/PIMPLE physical marching interval; ignored by SIMPLE
BASE_VELOCITY_RELAXATION = 0.7  # alpha_u: used by SIMPLE
BASE_PRESSURE_RELAXATION = 0.3  # alpha_p: used by SIMPLE
BASE_PRESSURE_CORRECTORS = 2   # N_i: PISO/PIMPLE inner corrections
BASE_OUTER_CORRECTORS = 3      # N_o: PIMPLE only
BASE_TOLERANCE = 1e-7          # native FV momentum AND divergence stopping threshold
BASE_MAX_ITERATIONS = 4000
BASE_CHECK_EVERY = 10          # evaluate native stopping tests every this many updates

if RUN_NEW:
    chosen = ["simple", "piso", "pimple"] if METHOD == "all" else [METHOD]
    fresh = [run_cavity(CavityConfig(method=m, cells=CELLS, dt=BASE_DT,
        velocity_relaxation=BASE_VELOCITY_RELAXATION,
        pressure_relaxation=BASE_PRESSURE_RELAXATION,
        pressure_correctors=BASE_PRESSURE_CORRECTORS,
        outer_correctors=BASE_OUTER_CORRECTORS, tolerance=BASE_TOLERANCE,
        max_iterations=BASE_MAX_ITERATIONS, check_every=BASE_CHECK_EVERY), progress=True)
        for m in chosen]
    tag = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + uuid4().hex[:8]
    folder = ROOT / "output/week01_2_baseline" / tag
    folder.mkdir(parents=True, exist_ok=True)
    for result in fresh:
        stem = result['config']['method'] + f"-n{CELLS}"
        archive = folder / (stem + ".npz")
        np.savez_compressed(archive, **{k:v for k,v in result.items() if isinstance(v,np.ndarray)})
        metadata = {k:v for k,v in result.items() if not isinstance(v,np.ndarray)}
        metadata['field_sha256'] = hashlib.sha256(archive.read_bytes()).hexdigest()
        (folder / (stem + ".json")).write_text(json.dumps(metadata,indent=2),encoding='utf-8')
    display(pd.DataFrame([{
        'method':r['config']['method'], 'native converged':r['converged'],
        'iterations':r['iterations'], 'seconds':r['runtime_seconds'],
        'momentum Linf':r['momentum_residual_linf'], 'divergence Linf':r['continuity_linf'],
        'report momentum gate':r['momentum_residual_linf']<1e-6,
        'report divergence gate':r['continuity_linf']<1e-9} for r in fresh]))
    active = [{**r, 'origin':'retained'} for r in recorded
              if r['config']['cells'] != CELLS or r['config']['method'] not in chosen]
    active += [{**r, 'origin':'fresh'} for r in fresh]
    order = ['simple','piso','pimple','streamfunction-vorticity']
    active.sort(key=lambda r:(r['config']['cells'],order.index(r['config']['method'])))
    same_mesh = [r for r in active if r['config']['cells']==CELLS]
    display(pd.DataFrame([{'origin':r['origin'], **r['config']} for r in same_mesh]))
    plain_names = {'simple':'SIMPLE','piso':'PISO','pimple':'PIMPLE',
                   'streamfunction-vorticity':'Streamfunction-vorticity'}
    plot_labels = {r['config']['method']:plain_names[r['config']['method']] +
                   ' [' + r['origin'] + ']' for r in same_mesh}
    provenance = '; '.join(plot_labels.values())
    for figure_i, (name,fig) in enumerate(figures(active,cells=CELLS,labels=plot_labels).items(),1):
        if name in {'runtime','grid_errors'}:
            plt.close(fig)
            continue
        display(fig)
        display(Markdown(f"**Experiment Figure E100-{figure_i}.** Re=100 {name}; h=1/{CELLS}. "
            f"Cases: {provenance}. Timings belong to their respective executions; rerun the "
            "compared methods on the same host before ranking wall time."))
        plt.close(fig)
    print('Saved full configurations and fields in', folder)
else:
    print('Retained results are shown above. Set RUN_NEW=True to launch a new FV solve.')

## Interpret the comparison
- Ghia velocity error is distinct from momentum and continuity residuals.
- All three FV methods should approach the same discrete steady solution.
- Agreement with the independent streamfunction formulation is a useful cross-check, not proof that either code is exact.
- Pressure mean must match before differences are compared. Ghia's velocity tables do not validate pressure.
- Two grids show a refinement trend; they do not establish an asymptotic order.
- FV and FD residual definitions differ, so their curves are not presented as the same norm.
- The singular lid corners need consistent boundary treatment; no cosmetic smoothing is applied.

## Exercises
1. Show interior face-flux cancellation in the domain mass budget.
2. Add a constant to pressure and confirm unchanged gradients and velocities.
3. Compare one and two PISO corrections using the physical-step momentum defect.
4. Verify PIMPLE with one outer loop matches PISO.
5. Change SIMPLE relaxation while keeping its final momentum tolerance fixed.
6. Compare upwind and central convection with the same coupling method.
7. Propose a dt-refinement experiment before claiming a PIMPLE speed advantage.

## Attribution
Independent implementation informed by [PySIMPLE](https://github.com/VishalKandala/PySIMPLE), [NIST FiPy's pressure-correction derivation](https://pages.nist.gov/fipy/en/latest/generated/examples.flow.stokesCavity.html), and [OpenFOAM pressure-velocity algorithms](https://www.openfoam.com/documentation/user-guide/6-solving/6.3-solution-and-algorithm-control). The [source notes](README.md) document the additional audited GitHub examples and their limitations. Ghia, Ghia and Shin (1982), DOI: 10.1016/0021-9991(82)90058-4.

## Higher-Reynolds-number investigation

How do resolution, convection interpolation and coupling settings change accuracy
and work at $Re=400$ and $1000$? `ExperimentalConfig` supports those values;
the baseline `CavityConfig` is qualified for Re=100.

**Cost and hardware.** Finer and higher-Re cases can take substantially longer
and require more memory and a stronger CPU. Doubling cells per side quadruples
the number of 2-D cells, and solve cost can grow faster. Begin with 32 cells,
one method and measured runtime before refining. Default figures load retained
results and launch no new CFD.

### An independent formulation

The streamfunction-vorticity method evolves vorticity, obtains streamfunction
from a Poisson equation, reconstructs velocity and recovers pressure afterward.
It provides an independent 2-D incompressible formulation. It uses different
unknown locations, equations and native stopping norms from the FV methods.
Compare physical spacing and centerline errors rather than treating its native
residual as an FV momentum defect.

**Reading the fields.** Black curves follow the computed velocity, even when
the color represents pressure or vorticity. Signed-field colors use symmetric
logarithmic normalization; speed is nonnegative and uses a linear scale.
Negative vorticity means clockwise local rotation. Seeds reveal resolved
recirculation but cannot create an unresolved vortex.

**Required sequence and deliverables**

1. Reproduce Re=100 first. Start Re=400 and 1000 on 32 cells and record settings,
   failed/nonconverged attempts and stopping reasons.
2. Refine to 64 cells; justify the cost before choosing 128. Compare both centerlines
   with the reference for the same Reynolds number.
3. Compare SIMPLE velocity relaxation (0.3/0.5/0.7), PISO inner corrections (1/2/4),
   or PIMPLE outer passes (1/2/3), changing one setting at a time. Keep spatial
   equations and final acceptance requirements fixed; record solve counts.
4. Compare central and first-order upwind at the same spacing and coupling method.
   The independent FD implementation supports central differences only.
5. Plot velocity structure, signed vorticity and zero-mean pressure; locate primary
   and resolved secondary vortices. A smoother field must still pass accuracy checks.

**Separate acceptance checks**

- FV: original steady momentum Linf below $10^{-6}$ and cell divergence below $10^{-9}$.
- FD: relative vorticity update below $10^{-12}$ at three checks, plus recomputed
  steady-vorticity RHS Linf below $10^{-6}$. Also report its independently computed divergence.
- All: finite fields, near-zero mean pressure, both reference-profile errors and
  spatial refinement evidence. The classroom 5% profile target is a chosen criterion.

The FV `tolerance` knob is used for both native stopping tests; it is not a separate
mass-tolerance setting. Report-level acceptance is checked again on returned fields.
`HIGHER_DT` applies to FV PISO/PIMPLE; `HIGHER_FD_DT` controls the independent FD step.

For Re=400, retain the published $v$-profile value at $x/L=0.9063$ but omit
that marked sample from the qualified error norm; report the all-point norm as well.
Ghia velocity tables do not supply an independent pressure benchmark.

The next cell verifies saved field hashes and displays benchmark diagnostics.
The retained field figures follow. The later opt-in cell exposes relaxation,
corrector counts and stopping controls and saves complete returned configurations.

[Measured higher-Re report](https://github.com/Ehsan-Roohi/FlowMLLab/blob/main/results/week01_2_formulations/README.md)

In [6]:
import json, hashlib
from flowmllab.pressure_velocity import centerlines, GHIA_X, GHIA_Y
from flowmllab.pressure_velocity_experiments import REFERENCE, benchmark_valid_mask

HIGH_RE = ROOT / "results/week01_2_formulations"
paths = sorted(HIGH_RE.glob("*-re*-n*.json"))
if not paths:
    raise FileNotFoundError("Retained higher-Re fields are missing; use a full FlowMLLab checkout.")

experimental_records, validated_rows, diagnostic_rows = [], [], []
for record_path in paths:
    record = json.loads(record_path.read_text())
    if record["status"] == "failed":
        continue
    archive = record_path.with_suffix(".npz")
    if hashlib.sha256(archive.read_bytes()).hexdigest() != record["field_sha256"]:
        raise ValueError(f"Field checksum does not match: {archive}")
    with np.load(archive, allow_pickle=False) as saved:
        run = {**record, **{key: saved[key] for key in saved.files}}
    re = int(run["config"]["reynolds"])
    y, u, x, v = centerlines(run)
    benchmark = np.asarray(REFERENCE[re]["v"])
    difference = np.interp(GHIA_X, x, v) - benchmark
    valid = benchmark_valid_mask(re, "v", GHIA_X)
    v_all = float(np.linalg.norm(difference) / np.linalg.norm(benchmark))
    v_qualified = float(np.linalg.norm(difference[valid]) /
                        np.linalg.norm(benchmark[valid]))
    # Check historical all-point archives and their separate qualified sensitivity.
    recorded_all = record.get("ghia_v_relative_l2_including_x09063",
                              record["ghia_v_relative_l2"])
    if not np.isclose(v_all, recorded_all, rtol=1e-9, atol=1e-12):
        raise ValueError(f"All-point Ghia metric mismatch: {record_path}")
    if re == 400 and not np.isclose(
        v_qualified, record["ghia_v_relative_l2_without_x09063"],
        rtol=1e-9, atol=1e-12
    ):
        raise ValueError(f"Qualified Ghia metric mismatch: {record_path}")
    experimental_records.append(record)
    validated_rows.append(run)
    diagnostic_rows.append({
        "method": run["config"]["method"], "Re": re,
        "cells": run["config"]["cells"], "status": run["status"],
        "Ghia u relative L2": run["ghia_u_relative_l2"],
        "Ghia v relative L2 (qualified)": v_qualified,
        "Ghia v relative L2 (all points)": v_all,
        "momentum Linf": run.get("momentum_residual_linf"),
        "divergence Linf": run.get("continuity_linf"),
    })
display(pd.DataFrame(diagnostic_rows))

                      method    Re  ...  momentum Linf divergence Linf
0                     pimple  1000  ...   9.516411e-07    6.671053e-14
1                     pimple   400  ...   9.139341e-07    9.389538e-14
2                       piso  1000  ...   8.970930e-07    6.861178e-14
3                       piso   400  ...   8.059235e-07    1.187262e-13
4                     simple  1000  ...   5.123548e-07    7.167877e-15
5                     simple  1000  ...   9.558379e-07    1.758576e-14
6                     simple   400  ...   7.832187e-07    6.704706e-15
7                     simple   400  ...   8.166014e-07    4.800760e-14
8   streamfunction-vorticity  1000  ...            NaN    7.105427e-15
9   streamfunction-vorticity  1000  ...            NaN    4.440892e-16
10  streamfunction-vorticity  1000  ...            NaN    3.552714e-15
11  streamfunction-vorticity   400  ...            NaN    7.105427e-15
12  streamfunction-vorticity   400  ...            NaN    1.554312e-15
13  streamfunction-vorticity   400  ...            NaN    3.552714e-15

[14 rows x 9 columns]

### Retained higher-Reynolds-number comparisons

![profiles re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/profiles_re400.png)

**Figure 17.** Retained Re=400 centerline velocities. Color identifies formulation and line style identifies spacing. Black markers are Ghia samples; the red cross retains the isolated published horizontal-profile anomaly at x/L=0.9063, excluded only from the qualified error norm. Selected fine cases do not constitute a complete refinement matrix.

![profiles re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/profiles_re1000.png)

**Figure 18.** Retained Re=1000 centerline velocities. Color identifies formulation and line style identifies spacing; black markers are Ghia et al. (1982) samples. Finer FD solutions show the effect of spatial resolution separately from the coupling algorithm.

![field speed re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_speed_re400.png)

**Figure S1.** Retained Re=400 speed at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Speed uses a linear color scale. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![field p re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_p_re400.png)

**Figure S2.** Retained Re=400 zero-mean pressure at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Signed fields use symmetric logarithmic normalization. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![field omega re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_omega_re400.png)

**Figure S3.** Retained Re=400 signed vorticity at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Signed fields use symmetric logarithmic normalization. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![convergence re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/convergence_re400.png)

**Figure S4.** Retained Re=400, h=1/32 convergence. Upper: FV steady momentum defect. Lower: FD relative vorticity-update rate, divided by its time step. The equations, iteration units and stopping norms differ; their ordinate magnitudes cannot be used to rank formulation accuracy. Recorded costs are in the tables.

![field speed re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_speed_re1000.png)

**Figure S5.** Retained Re=1000 speed at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Speed uses a linear color scale. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![field p re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_p_re1000.png)

**Figure S6.** Retained Re=1000 zero-mean pressure at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Signed fields use symmetric logarithmic normalization. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![field omega re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/field_omega_re1000.png)

**Figure S7.** Retained Re=1000 signed vorticity at h=1/32, with computed velocity streamlines. All four formulations are shown on the same physical color scale. Signed fields use symmetric logarithmic normalization. These coarse-grid solutions are distinct from the selected fine-grid comparisons.

![convergence re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/convergence_re1000.png)

**Figure S8.** Retained Re=1000, h=1/32 convergence. Upper: FV steady momentum defect. Lower: FD relative vorticity-update rate, divided by its time step. The equations, iteration units and stopping norms differ; their ordinate magnitudes cannot be used to rank formulation accuracy. Recorded costs are in the tables.

In [ ]:
from IPython.display import Markdown
from datetime import datetime, timezone
from dataclasses import asdict
from uuid import uuid4
import hashlib, json

RUN_HIGHER_RE = False
HIGHER_RE = 400
HIGHER_CELLS = 32
HIGHER_METHOD = "all"  # all four formulations, or one method name
HIGHER_SCHEME = "central"  # central / upwind; independent FD supports central only
HIGHER_DT = 0.05           # FV PISO/PIMPLE interval; ignored by steady SIMPLE
HIGHER_VELOCITY_RELAXATION = 0.5  # SIMPLE alpha_u
HIGHER_PRESSURE_RELAXATION = 0.2  # SIMPLE alpha_p
HIGHER_PRESSURE_CORRECTORS = 2    # PISO/PIMPLE inner corrections
HIGHER_OUTER_CORRECTORS = 3       # PIMPLE outer passes
HIGHER_TOLERANCE = 1e-6           # native FV momentum AND divergence threshold
HIGHER_MAX_ITERATIONS = 4000
HIGHER_CHECK_EVERY = 10
HIGHER_FD_DT = 0.001              # independent FD physical time step
HIGHER_FD_MAX_STEPS = 400000

if RUN_HIGHER_RE:
    from flowmllab.pressure_velocity_experiments import ExperimentalConfig, run_experiment
    from flowmllab.streamfunction_experiments import run_streamfunction
    methods = ["simple","piso","pimple","streamfunction-vorticity"] if HIGHER_METHOD=="all" else [HIGHER_METHOD]
    higher_runs, higher_summary = [], []
    tag = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + uuid4().hex[:8]
    save_root = ROOT / "output/week01_2_higher_re" / tag
    save_root.mkdir(parents=True,exist_ok=True)
    for m in methods:
        if m == 'streamfunction-vorticity':
            attempted = dict(method=m,reynolds=HIGHER_RE,cells=HIGHER_CELLS,
                dt=HIGHER_FD_DT,max_steps=HIGHER_FD_MAX_STEPS,convection=HIGHER_SCHEME,
                relative_update_tolerance=1e-12,check_every=500,consecutive_required=3)
        else:
            attempted = dict(method=m,reynolds=HIGHER_RE,cells=HIGHER_CELLS,
                convection=HIGHER_SCHEME,dt=HIGHER_DT,
                velocity_relaxation=HIGHER_VELOCITY_RELAXATION,
                pressure_relaxation=HIGHER_PRESSURE_RELAXATION,
                pressure_correctors=HIGHER_PRESSURE_CORRECTORS,
                outer_correctors=HIGHER_OUTER_CORRECTORS,tolerance=HIGHER_TOLERANCE,
                max_iterations=HIGHER_MAX_ITERATIONS,check_every=HIGHER_CHECK_EVERY)
        stem = f"{m}-re{HIGHER_RE}-n{HIGHER_CELLS}-{HIGHER_SCHEME}"
        try:
            if m == 'streamfunction-vorticity':
                if HIGHER_SCHEME != 'central':
                    raise ValueError('The independent FD formulation uses central differences; choose central for all four methods.')
                r = run_streamfunction(HIGHER_RE,HIGHER_CELLS,dt=HIGHER_FD_DT,
                                      max_steps=HIGHER_FD_MAX_STEPS,progress=True)
            else:
                config = ExperimentalConfig(**attempted)
                attempted = asdict(config)
                r = run_experiment(config,progress=True)
            higher_runs.append(r)
            summary = {**r['config'], **{k:r.get(k) for k in [
                'converged','iterations','steps','steady_vorticity_linf','runtime_seconds',
                'pressure_solves','momentum_residual_linf','continuity_linf',
                'ghia_u_relative_l2','ghia_v_relative_l2']}}
            summary['report divergence gate'] = r['continuity_linf'] < 1e-9
            if m == 'streamfunction-vorticity':
                summary['report native gate'] = r['update_converged'] and r['steady_vorticity_linf'] < 1e-6
            else:
                summary['report native gate'] = r['momentum_residual_linf'] < 1e-6
            higher_summary.append(summary)
            archive = save_root / (stem+'.npz')
            np.savez_compressed(archive, **{k:v for k,v in r.items() if isinstance(v,np.ndarray)})
            metadata = {k:v for k,v in r.items() if not isinstance(v,np.ndarray)}
            metadata['field_sha256'] = hashlib.sha256(archive.read_bytes()).hexdigest()
            (save_root/(stem+'.json')).write_text(json.dumps(metadata,indent=2),encoding='utf-8')
        except Exception as error:
            failure = {'config':attempted,'converged':False,'error':str(error)}
            higher_summary.append({**attempted,'converged':False,'error':str(error)})
            (save_root/(stem+'-failed.json')).write_text(json.dumps(failure,indent=2),encoding='utf-8')
    higher_table = pd.DataFrame(higher_summary)
    display(higher_table)
    higher_table.to_csv(save_root/'summary.csv',index=False)
    print('Saved configurations, successful/nonconverged fields and failure records in',save_root)
    from flowmllab.pressure_velocity_experiment_plots import comparison_figures
    if higher_runs:
        for figure_i,(name,figure) in enumerate(comparison_figures(higher_runs).items(),1):
            display(figure)
            display(Markdown(f"**Experiment Figure EH-{figure_i}.** Fresh Re={HIGHER_RE} {name}; "
                f"h=1/{HIGHER_CELLS}, convection={HIGHER_SCHEME}. Settings and native stopping "
                "definitions are preserved in the case JSON and table; FD and FV norms differ."))
            plt.close(figure)
else:
    print('Retained higher-Re results are displayed above. Set RUN_HIGHER_RE=True to recompute.')

### Submit your analysis

Submit one configuration/result CSV (including failed runs), the centerline,
field and convergence figures, and a short explanation addressing:
- Does refinement improve both centerlines? Does upwind change the answer?
- At the same discrete accuracy, do extra corrections repay their solve cost?
- Are low mass residuals accompanied by small momentum and benchmark errors?
- If a case fails, does changing dt, relaxation or the mesh isolate its cause?

Do not claim turbulence, a universal fastest method, or a maximum usable Re
from this two-dimensional steady study. A time-accurate comparison needs a
separate dt-refinement study with within-step convergence checks.

## Independent formulation: streamfunction-vorticity at Re=400 and 1000

**Question:** does the independent Week-1 formulation give the same physical
flow, and what accuracy and computation cost do we obtain?

The retained study contains independently executed runs from rest for all
four formulations, using central differences at matched spacing h=1/32.
FD uses 33x33 boundary-inclusive nodes; FV uses 32x32 pressure cells.
The default loads those records. The optional cell below recomputes an FD case.
Pressure in FD is recovered after velocity convergence.

The two-dimensional formulation uses

$$
u=\frac{\partial\psi}{\partial y},\qquad
v=-\frac{\partial\psi}{\partial x},\qquad
\nabla^2\psi=-\omega,
$$

$$
\frac{\partial\omega}{\partial t}
+u\frac{\partial\omega}{\partial x}
+v\frac{\partial\omega}{\partial y}
=\frac{1}{Re}\nabla^2\omega.
$$

Velocity is reconstructed from psi; pressure is absent from these evolution
equations. In the pressure-velocity methods, continuity instead supplies the
pressure-correction equation coupled to momentum.

**Convergence:** FV stops on momentum Linf <1e-6; FD stops on a relative
vorticity update <1e-12 at three checks and also passes a recomputed steady
vorticity RHS Linf <1e-6. Native residuals have different meanings and are
shown on separate panels. Ghia velocity errors provide the shared accuracy
comparison. Re=400 keeps the anomalous published v value and reports its
one-point omission sensitivity separately. Pressure has no Ghia benchmark.

**Timing:** sequential single-thread runs, one sample per setting; the timed
solver call includes FD pressure recovery. Different dt, equations, stopping
norms and unknown counts preclude a universal fastest-method claim. Compare
accuracy before interpreting seconds. The field panels show all four
methods with velocity streamlines and visible resolved corner recirculation.

**Retained failures:** the initial Re=400 update-only stop failed the steady
RHS check, and Re=1000 exhausted its first step budget. Both original fields
and logs remain in `attempts/`; reruns tighten the update tolerance without
relaxing the steady gate. The report includes a separate 64-cell SIMPLE/FD
mesh check plus an FD-only 128-cell refinement; PISO/PIMPLE are compared at
32 cells only. The fine-grid panels label each spacing explicitly.

**Student tasks:** compare both centerline errors and corner vortices; explain
why zero integrated/local mass error does not prove momentum accuracy; explain
why FD update and FV momentum histories cannot share an unlabeled residual
axis. Refine the FD mesh to investigate its own accuracy trend. Do not compare
fine-grid FD time to coarse-grid FV time as equal work. Finer and higher-Re
runs can take longer and need more memory/stronger hardware.

[Full report and raw results](https://github.com/Ehsan-Roohi/FlowMLLab/tree/main/results/week01_2_formulations)

### FD pressure-gradient discrepancy

The FD formulation recovers pressure after the velocity solve. This quantity is
the RMS vector mismatch between the gradient of recovered pressure and the
pressure-gradient field inferred from steady momentum, divided by the latter's
RMS magnitude. RMS is the square root of the mean squared vector magnitude over
the grid. It tests recovery consistency; it is not a Ghia pressure error.

In [7]:
from IPython.display import Markdown
import json
FORMULATIONS = ROOT / "results/week01_2_formulations"
formulation_records = [json.loads(p.read_text()) for p in sorted(FORMULATIONS.glob("*-re*-n*.json"))]
if not formulation_records:
    raise FileNotFoundError("A complete current checkout needs results/week01_2_formulations")
display(pd.DataFrame([{
    "Re": r["config"]["reynolds"], "method": r["config"]["method"],
    "cells per side": r["config"]["cells"], "status": r["status"],
    "end-to-end seconds": r["end_to_end_seconds"],
    "steps / iterations": r.get("steps", r.get("iterations")),
    "u Ghia rel L2": r.get("ghia_u_relative_l2"),
    "v Ghia rel L2 (qualified)": r.get("ghia_v_relative_l2_without_x09063",
                                         r.get("ghia_v_relative_l2")),
    "v Ghia rel L2 (all points)": r.get("ghia_v_relative_l2_including_x09063",
                                          r.get("ghia_v_relative_l2")),
    "FV momentum Linf": r.get("momentum_residual_linf"),
    "FD steady vorticity RHS Linf": r.get("steady_vorticity_linf"),
    "continuity Linf": r.get("continuity_linf"),
    "FD pressure-gradient discrepancy": r.get("pressure_grad_rel_residual"),
} for r in formulation_records]).fillna("n/a"))

# Fresh independent FD run: opt in deliberately. These can take minutes.
RUN_STREAMFUNCTION = False
STREAM_RE = 400
STREAM_CELLS = 32
if RUN_STREAMFUNCTION:
    from flowmllab.streamfunction_experiments import run_streamfunction
    from flowmllab.pressure_velocity import centerlines, GHIA_Y
    from flowmllab.pressure_velocity_experiments import REFERENCE
    from flowmllab.cavity_visuals import RGB, flow_structure
    import hashlib
    sf = run_streamfunction(STREAM_RE, STREAM_CELLS, progress=True)
    folder = ROOT / "output/week01_2_streamfunction"
    folder.mkdir(parents=True, exist_ok=True)
    stem = f"streamfunction-re{STREAM_RE}-n{STREAM_CELLS}"
    archive = folder / (stem + ".npz")
    np.savez_compressed(archive, **{k:v for k,v in sf.items() if isinstance(v,np.ndarray)})
    metadata = {k:v for k,v in sf.items() if not isinstance(v,np.ndarray)}
    metadata["field_sha256"] = hashlib.sha256(archive.read_bytes()).hexdigest()
    (folder / (stem + ".json")).write_text(json.dumps(metadata,indent=2))
    display(pd.DataFrame([{k:sf[k] for k in ["status", "runtime_seconds", "steps",
        "steady_vorticity_linf", "continuity_linf", "ghia_u_relative_l2", "ghia_v_relative_l2"]}]))
    y,u,x,v = centerlines(sf)
    fig,axes=plt.subplots(1,2,figsize=(10,4),layout="constrained")
    axes[0].plot(u,y,label="Fresh FD")
    axes[0].plot(REFERENCE[STREAM_RE]["u"],GHIA_Y,"ko",label="Ghia")
    axes[0].set(xlabel="u / U",ylabel="y / L");axes[0].legend()
    image = axes[1].pcolormesh(sf["x"],sf["y"],np.hypot(sf["u"],sf["v"]),cmap=RGB,shading="nearest")
    fig.colorbar(image,ax=axes[1],label="Speed / U")
    flow_structure(axes[1],sf["x"],sf["y"],sf["u"],sf["v"])
    axes[1].set(aspect="equal",xlabel="x / L",ylabel="y / L",title="Fresh speed and streamlines")
    display(fig)
    display(Markdown(f"**Experiment Figure EFD-1.** Fresh streamfunction-vorticity velocity profile and speed with streamlines, Re={STREAM_RE}, h=1/{STREAM_CELLS}. Black profile markers are Ghia reference samples."))
    plt.close(fig)
    print("Saved", folder, "; retain failed/nonconverged results too.")

      Re  ... FD pressure-gradient discrepancy
0   1000  ...                              n/a
1    400  ...                              n/a
2   1000  ...                              n/a
3    400  ...                              n/a
4   1000  ...                              n/a
5   1000  ...                              n/a
6    400  ...                              n/a
7    400  ...                              n/a
8   1000  ...                         0.641287
9   1000  ...                          0.81618
10  1000  ...                         0.724257
11   400  ...                         0.555028
12   400  ...                         0.732052
13   400  ...                          0.63534

[14 rows x 13 columns]

### Selected spatial refinement

![refinement re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/refinement_re400.png)

**Figure 19.** Retained Re=400 speed and computed velocity streamlines: SIMPLE at h=1/64, and independent streamfunction-vorticity solutions at h=1/64 and 1/128. The color scale and lid speed are common. Small recirculation structures must be supported by the resolved velocity field.

![refinement re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/refinement_re1000.png)

**Figure 20.** Retained Re=1000 speed and computed velocity streamlines for the same selected refinement cases. The finer grid changes resolved boundary layers and corner circulation. Additional pressure corrections alone cannot recover spatial structures absent from the mesh.

## Worked study: a converged solution can still need a finer grid

The student's October 2026 cavity report compares SIMPLE, PISO and PIMPLE
on 32 and 64 cells per side at $Re=400$ and 1000. The table below preserves his
reported measurements. Separate retained reproduction runs check selected cases with
the current solver; the two sets of timings are not interchangeable.

The report's momentum defects are below $10^{-6}$ and cell divergences below
$10^{-9}$. Nevertheless, at $Re=1000$ on 32 cells it reports 8.67% error in
$u$ and 14.15% in $v$. On 64 cells those decrease to 2.59% and 3.46%.
The chosen 5% profile target is a classroom criterion, not a universal standard.
For $Re=400$, the scored $v$ norm excludes the published anomaly at
$x/L=0.9063$; its original value is retained and marked in the plots.

**Read the profiles as well as the numbers.** At fixed grid and spatial
scheme, the three converged coupling methods approach the same discrete
steady problem. Refining the grid changes how the flow is represented. Two
grids show a refinement trend, not a verified order of accuracy.

The retained reproduction suite includes all three methods on 32 cells for each Reynolds
number, SIMPLE on 64 cells for each Reynolds number, and matched central/upwind
SIMPLE on 32 cells at $Re=400$. The four 64-cell PISO/PIMPLE submissions are
not independently rerun here. Original student arrays, full configuration and
machine specifications were not attached, so exact source-run replication and
timing replication cannot be claimed.

[Reviewed explanations, corrections and provenance](https://github.com/Ehsan-Roohi/FlowMLLab/blob/main/docs/reviews/student_cavity_20261026.md)

**Exercises**

1. From the table, distinguish passing the equation-defect targets from passing
   both profile-error targets. Explain the difference physically.
2. Divide pressure solves by reported iterations. Explain why the ratios are
   1 for SIMPLE, 2 for PISO and 6 for PIMPLE in these runs.
3. Locate where the fine-grid velocity profiles differ from the coarse ones.
   Compare this change with switching the coarse-grid coupling method.
4. Compare central and upwind at the same grid, Reynolds number and method.
   Do the measured profiles support the numerical-diffusion explanation?
5. Design a time-step refinement study before claiming a transient advantage
   for PIMPLE. Extra coupling loops do not increase backward Euler's time order.

The following cell loads small retained tables and figures; it does not launch
new CFD. Recomputing the nine-case suite with
`python qa/review_student_cavity.py --run` may take several minutes or longer on
a CPU. Begin with the retained evidence before running finer grids.

In [8]:
from IPython.display import display, Image
study = ROOT / "results/week01_2_student_review"
submitted = pd.read_csv(study / "submitted_summary.csv")
fresh = pd.read_csv(study / "fresh_summary.csv")
print("Student-reported central-convection measurements (12 cases):")
display(submitted)
print("Retained independent reproduction measurements (9 cases; separate timings):")
display(fresh)
keys = ["method", "reynolds", "cells", "convection"]
checked = submitted.merge(fresh, on=keys, how="inner")
checked["fresh u error percent"] = 100 * checked["ghia_u_relative_l2"]
checked["fresh v error percent"] = 100 * checked["ghia_v_relative_l2"]
display(checked[keys + ["reported_u_error_percent", "fresh u error percent",
                       "reported_v_error_percent", "fresh v error percent"]])
print("Shared cases compare rounded reported errors with field-derived reproduction errors.")

Student-reported central-convection measurements (12 cases):
Retained independent reproduction measurements (9 cases; separate timings):
Shared cases compare rounded reported errors with field-derived reproduction errors.

    report_page  method  ...  reported_v_error_percent     v_reference_policy
0             1  simple  ...                      8.43       exclude_x_0.9063
1             2  simple  ...                      1.85       exclude_x_0.9063
2             3    piso  ...                      8.43       exclude_x_0.9063
3             4    piso  ...                      1.85       exclude_x_0.9063
4             5  pimple  ...                      8.43       exclude_x_0.9063
5             6  pimple  ...                      1.85       exclude_x_0.9063
6             7  simple  ...                     14.15  all_tabulated_samples
7             8  simple  ...                      3.46  all_tabulated_samples
8             9    piso  ...                     14.15  all_tabulated_samples
9            10    piso  ...                      3.46  all_tabulated_samples
10           11  pimple  ...                     14.15  all_tabulated_samples
11           12  pimple  ...                      3.46  all_tabulated_samples

[12 rows x 13 columns]

   method  reynolds  ...  ghia_u_relative_l2 ghia_v_relative_l2
0  pimple      1000  ...            0.086748           0.141515
1  pimple       400  ...            0.036075           0.084338
2    piso      1000  ...            0.086748           0.141515
3    piso       400  ...            0.036074           0.084336
4  simple      1000  ...            0.086743           0.141507
5  simple      1000  ...            0.025904           0.034642
6  simple       400  ...            0.036073           0.084333
7  simple       400  ...            0.138720           0.311102
8  simple       400  ...            0.008341           0.018532

[9 rows x 11 columns]

   method  reynolds  ...  reported_v_error_percent fresh v error percent
0  simple       400  ...                      8.43              8.433270
1  simple       400  ...                      1.85              1.853234
2    piso       400  ...                      8.43              8.433574
3  pimple       400  ...                      8.43              8.433751
4  simple      1000  ...                     14.15             14.150699
5  simple      1000  ...                      3.46              3.464211
6    piso      1000  ...                     14.15             14.151516
7  pimple      1000  ...                     14.15             14.151507

[8 rows x 8 columns]

### Independent follow-up calculations

![review profiles re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/review_profiles_re400.png)

**Figure S9.** Independent follow-up Re=400 velocity profiles for central convection. Solid lines use 32 FV cells per side; dashed lines use 64 where available. Black markers are Ghia samples. At Re=400 the red cross retains the isolated published anomaly without including it in the qualified norm. These fields and their timings belong to the separately identified follow-up suite.

![review coupling re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/review_coupling_re400.png)

**Figure S10.** Independent follow-up Re=400, 32-cell central-convection histories against cumulative pressure solves. The dotted momentum line is the 1e-6 target. Divergence fluctuations near machine precision are not spatial error. Solve count is a work indicator, not an assertion that every linear solve has equal cost.

![review profiles re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/review_profiles_re1000.png)

**Figure S11.** Independent follow-up Re=1000 velocity profiles for central convection. Solid lines use 32 FV cells per side; dashed lines use 64 where available. Black markers are Ghia samples. These fields and their timings belong to the separately identified follow-up suite.

![review coupling re1000](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/review_coupling_re1000.png)

**Figure S12.** Independent follow-up Re=1000, 32-cell central-convection histories against cumulative pressure solves. The dotted momentum line is the 1e-6 target. Divergence fluctuations near machine precision are not spatial error. Solve count is a work indicator, not an assertion that every linear solve has equal cost.

![review convection re400](https://raw.githubusercontent.com/Ehsan-Roohi/FlowMLLab/main/lectures/source/week01_2_assets/review_convection_re400.png)

**Figure S13.** Independent follow-up Re=400 SIMPLE profiles: first-order upwind and central convection on the indicated meshes. Changing convection changes the spatial equations; this is separate from changing the pressure-velocity coupling algorithm. The isolated Ghia horizontal-profile anomaly is omitted from the qualified markers.

## Guided reading and video lectures

1. **Momentum to pressure correction:** Greenshields and Weller, [CFD Direct, section 5.10](https://doc.cfd.direct/notes/cfd-general-principles/pressure-velocity-coupling). Follow the momentum diagonal, flux correction and substitution into continuity beside this notebook's scalar derivation.
2. **SIMPLE:** [CFD Direct, section 5.12](https://doc.cfd.direct/notes/cfd-general-principles/steady-state-solution) and Fluid Mechanics 101, [The SIMPLE Algorithm (YouTube)](https://www.youtube.com/watch?v=OOILoJ1zuiw). Identify the predictor, pressure correction, under-relaxation and next nonlinear iteration.
3. **PISO:** [CFD Direct, section 5.19](https://doc.cfd.direct/notes/cfd-general-principles/transient-solution) and Fluid Mechanics 101, [The PISO Algorithm (YouTube)](https://www.youtube.com/watch?v=ahdW5TKacok). Track which correction terms change while old-time data and momentum coefficients stay fixed. The video's non-orthogonal corrections address a separate mesh issue, absent on this uniform Cartesian grid.
4. **PIMPLE:** [CFD Direct, section 5.21](https://doc.cfd.direct/notes/cfd-general-principles/the-pimple-algorithm). Compare inner corrections with outer coefficient updates. Distinguish a time-accurate transient from a pseudo-transient steady calculation.
5. **Practical controls:** [OpenFOAM v13 User Guide, Solution and algorithm control](https://doc.cfd.direct/openfoam/user-guide-v13/fvsolution). Map `nCorrectors`, `nOuterCorrectors` and the pressure reference to the diagrams. Software defaults and collocated interpolation details differ from this Python MAC solver.

The [Fluid Mechanics 101 catalogue](https://www.fluidmechanics101.com/pages/lectures.html) lists the free YouTube lectures separately from paid slide collections. Paid slides are not required here. Figures 1-20 share identifiers with the lecture PDF; S-numbered figures are notebook supplements. The numerical examples above use the equations and conventions derived in this notebook.